import React from 'react';
import { Layers, MessageCircle } from 'lucide-react';

// --- Custom Game Logos (SVGs) ---

export const ValorantLogo = ({ className }: { className?: string }) => (
  <svg viewBox="0 0 24 24" fill="currentColor" className={className}>
    {/* Right shape */}
    <path d="M22 3.5h-4.3L9.6 22h4.2l8.2-18.5z" />
    {/* Left shape */}
    <path d="M2 3.5h4.8l2.9 6.9-7.7-6.9z" />
  </svg>
);

export const ApexLogo = ({ className }: { className?: string }) => (
  <svg viewBox="0 0 24 24" fill="currentColor" className={className}>
    {/* Main A shape with cutouts */}
    <path d="M12 2.5L2.8 19.5h3.8l1.7-3.3h7.4l1.7 3.3h3.8L12 2.5zm-.9 9.8L12 10l.9 2.3h-1.8z" />
    {/* Bottom bar if needed, but the main A shape is iconic enough */}
  </svg>
);

export const OWLogo = ({ className }: { className?: string }) => (
  <svg viewBox="0 0 24 24" fill="currentColor" className={className}>
    {/* Top Arc */}
    <path d="M12 2.5c-4.8 0-8.8 3.6-9.4 8.2h3.9c.5-2.5 2.7-4.3 5.5-4.3s5 1.9 5.5 4.3h3.9c-.6-4.6-4.6-8.2-9.4-8.2z" />
    {/* Left Arm */}
    <path d="M5.7 12.8c.9 3.6 4 6.5 7.7 7.2l-1.9-4.8-1.7-1.7H5.7z" />
    {/* Right Arm */}
    <path d="M18.3 12.8h-4.2l-1.7 1.7-1.9 4.8c3.8-.7 6.8-3.6 7.8-7.2z" />
  </svg>
);

export interface Category {
  id: string;
  name: string;
  name_tw: string; // Taiwan Traditional
  name_hk?: string; // Hong Kong Traditional
  icon: React.ReactNode;
  color: string;
}

export interface VocabItem {
  id: string;
  cat: string;
  term: string;
  kana: string;
  romaji: string;
  level: number;
  meaning: string;
  meaning_tw?: string; // Taiwan meaning
  meaning_hk?: string; // HK meaning
  desc: string;
  desc_tw?: string;    // Taiwan description
  desc_hk?: string;    // HK description
  example: string;
  example_tw?: string; // Taiwan example
  example_hk?: string; // HK example
  alt?: string[];      // Optional alternative writings
  tags?: string[];     // Scene tags (e.g., 'Combat', 'Loot')
  stars?: number;      // Frequency: 1, 2, or 3
}

export const CATEGORIES: Category[] = [
  { id: 'ALL', name: '综合', name_tw: '綜合', name_hk: '綜合', icon: <Layers className="w-5 h-5" />, color: 'text-white border-white/30 bg-white/10' },
  { id: 'LIFE', name: '常用/网络', name_tw: '常用/網路', name_hk: '常用/網絡', icon: <MessageCircle className="w-5 h-5" />, color: 'text-fuchsia-400 border-fuchsia-500/30 bg-fuchsia-500/10' },
  { id: 'VALORANT', name: '瓦罗兰特', name_tw: '特戰英豪', name_hk: 'Valorant', icon: <ValorantLogo className="w-5 h-5" />, color: 'text-rose-400 border-rose-500/30 bg-rose-500/10' },
  { id: 'APEX', name: 'APEX', name_tw: 'Apex 英雄', name_hk: 'Apex 英雄', icon: <ApexLogo className="w-5 h-5" />, color: 'text-red-400 border-red-500/30 bg-red-500/10' },
  { id: 'OW', name: '守望先锋', name_tw: '鬥陣特攻', name_hk: '鬥陣特攻', icon: <OWLogo className="w-5 h-5" />, color: 'text-orange-400 border-orange-500/30 bg-orange-500/10' },
];

// --- Scene Definitions ---
export const SCENE_TAGS: Record<string, { id: string; label: string; label_tw: string; label_hk: string }[]> = {
  LIFE: [
    { id: 'SOCIAL', label: '社交', label_tw: '社交', label_hk: '社交' },
    { id: 'EMOTION', label: '情绪', label_tw: '情緒', label_hk: '情緒' },
    { id: 'SLANG', label: '俚语', label_tw: '俚語', label_hk: '潮語' },
    { id: 'LOVE', label: '恋爱', label_tw: '戀愛', label_hk: '拍拖' },
    { id: 'SCHOOL', label: '校园', label_tw: '校園', label_hk: '校園' },
  ],
  VALORANT: [
    { id: 'CALLOUT', label: '报点', label_tw: '報點', label_hk: '報點' },
    { id: 'SKILL', label: '技能', label_tw: '技能', label_hk: '技能' },
    { id: 'TACTIC', label: '战术', label_tw: '戰術', label_hk: '戰術' },
    { id: 'ECON', label: '经济', label_tw: '經濟', label_hk: '經濟' },
    { id: 'SYSTEM', label: '系统', label_tw: '系統', label_hk: '系統' },
  ],
  APEX: [
    { id: 'CALLOUT', label: '报点', label_tw: '報點', label_hk: '報點' },
    { id: 'SKILL', label: '技能', label_tw: '技能', label_hk: '技能' },
    { id: 'LOOT', label: '装备', label_tw: '裝備', label_hk: '裝備' },
    { id: 'HELP', label: '求助', label_tw: '求助', label_hk: '求助' },
    { id: 'OUTCOME', label: '胜负', label_tw: '勝負', label_hk: '勝負' },
  ],
  OW: [
    { id: 'ULT', label: '大招', label_tw: '大絕', label_hk: '大絕' },
    { id: 'COMBAT', label: '战斗', label_tw: '戰鬥', label_hk: '戰鬥' },
    { id: 'ROLE', label: '职责', label_tw: '職責', label_hk: '職責' },
    { id: 'SYSTEM', label: '系统', label_tw: '系統', label_hk: '系統' },
  ]
};

export const VOCAB_DATA: VocabItem[] = [
  // ================= LIFE (常用/Tameguchi/网络) =================
  { "id": "l01", "cat": "LIFE", "term": "それな", "kana": "それな", "romaji": "Sorena", "level": 1, "meaning": "确实 / 懂你 / +1", "meaning_tw": "真的 / 中肯 / +1", "meaning_hk": "係囉 / 堅 / 真心", "desc": "【万能】表示强烈赞同。", "desc_tw": "【萬能】表示強烈贊同。", "desc_hk": "【萬能】表示極度贊同。", "example": "A: 眠い...(好困...)\nB: それな。(确实。)", "example_tw": "A: 眠い...(好睏...)\nB: それな。(真的。)", "example_hk": "A: 眠い...(好眼訓...)\nB: それな。(係囉。)", "tags": ["SOCIAL"], "stars": 3 },
  { "id": "l02", "cat": "LIFE", "term": "まじで", "kana": "まじで", "romaji": "Majide", "level": 1, "meaning": "真的假的？", "meaning_tw": "真假？/ 真的假的？", "meaning_hk": "堅定流？/ 真定假？", "desc": "【惊讶】不敢相信。", "desc_tw": "【驚訝】不敢相信。", "desc_hk": "【驚訝】唔敢相信。", "example": "A: 宝くじ当たった。(中彩票了)\nB: まじで？すご！(真的假的？好厉害！)", "example_tw": "A: 宝くじ当たった。(中樂透了)\nB: まじで？すご！(真假？好厲害！)", "example_hk": "A: 宝くじ当たった。(中六合彩呀)\nB: まじで？すご！(堅定流？勁喎！)", "tags": ["EMOTION"], "stars": 3 },
  { "id": "l03", "cat": "LIFE", "term": "わかる", "kana": "わかる", "romaji": "Wakaru", "level": 1, "meaning": "我懂 / 理解", "meaning_tw": "我懂 / 理解", "meaning_hk": "明啊 / 理解", "desc": "【共情】深有同感。", "desc_tw": "【共情】深有同感。", "desc_hk": "【共情】深有同感。", "example": "A: ラーメン食べたい。(想吃拉面)\nB: わかる〜。(懂你~)", "example_tw": "A: ラーメン食べたい。(想吃拉麵)\nB: わかる〜。(懂你~)", "example_hk": "A: ラーメン食べたい。(想食拉麵)\nB: わかる〜。(明啊~)", "tags": ["SOCIAL"], "stars": 3 },
  { "id": "l04", "cat": "LIFE", "term": "うそ", "kana": "うそ", "romaji": "Uso", "level": 1, "meaning": "骗人 / 不会吧", "meaning_tw": "騙人 / 不會吧", "meaning_hk": "呃人 / 唔係掛", "desc": "【惊讶】表示怀疑。", "desc_tw": "【驚訝】表示懷疑。", "desc_hk": "【驚訝】表示懷疑。", "example": "A: 明日テストだって。(听说明天考试)\nB: うそでしょ！？(骗人的吧！？)", "example_tw": "A: 明日テストだって。(聽說明天考試)\nB: うそでしょ！？(騙人的吧！？)", "example_hk": "A: 明日テストだって。(聽講聽日測驗)\nB: うそでしょ！？(唔係掛！？)", "tags": ["EMOTION"], "stars": 2 },
  { "id": "l05", "cat": "LIFE", "term": "なるほど", "kana": "なるほど", "romaji": "Naruhodo", "level": 1, "meaning": "原来如此", "meaning_tw": "原來如此", "meaning_hk": "原來係咁", "desc": "【理解】表示听懂了。", "desc_tw": "【理解】表示聽懂了。", "desc_hk": "【理解】表示聽明咗。", "example": "A: ここを押すんだよ。(按这里)\nB: あ〜なるほどね。(啊~原来如此)", "example_tw": "A: ここを押すんだよ。(按這裡)\nB: あ〜なるほどね。(啊~原來如此)", "example_hk": "A: ここを押すんだよ。(撳呢度)\nB: あ〜なるほどね。(啊~原來係咁)", "tags": ["SOCIAL"], "stars": 3 },
  { "id": "l06", "cat": "LIFE", "term": "たしかに", "kana": "たしかに", "romaji": "Tashikani", "level": 1, "meaning": "确实 / 有道理", "meaning_tw": "確實 / 有道理", "meaning_hk": "又係喎 / 確實", "desc": "【赞同】被对方说服时。", "desc_tw": "【贊同】被對方說服時。", "desc_hk": "【贊同】被對方說服時。", "example": "A: こっちの方が早いよ。(这边比较快)\nB: 言われてみればたしかに。(确实是这样)", "example_tw": "A: こっちの方が早いよ。(這邊比較快)\nB: 言われてみればたしかに。(確實是這樣)", "example_hk": "A: こっちの方が早いよ。(呢邊快啲)\nB: 言われてみればたしかに。(又係喎)", "tags": ["SOCIAL"], "stars": 2 },
  { "id": "l07", "cat": "LIFE", "term": "やばい", "kana": "やばい", "romaji": "Yabai", "level": 1, "meaning": "糟糕 / 厉害 / 绝了", "meaning_tw": "糟糕 / 厲害 / 絕了", "meaning_hk": "大鑊 / 勁 / 世一", "desc": "【万能】好坏皆可。", "desc_tw": "【萬能】好壞皆可。", "desc_hk": "【萬能】好壞都用得。", "example": "A: 新曲聴いた？(听新歌了吗)\nB: この曲やばい！(这歌太绝了！)", "example_tw": "A: 新曲聴いた？(聽新歌了嗎)\nB: この曲やばい！(這歌太絕了！)", "example_hk": "A: 新曲聴いた？(聽咗新歌未)\nB: この曲やばい！(呢首世一！)", "tags": ["SLANG", "EMOTION"], "stars": 3 },
  { "id": "l08", "cat": "LIFE", "term": "エグい", "kana": "えぐい", "romaji": "Egui", "level": 2, "meaning": "太狠了 / 离谱", "meaning_tw": "太狠了 / 離譜 / 誇張", "meaning_hk": "痴線 / 好癲", "desc": "【程度】程度极深。", "desc_tw": "【程度】程度極深。", "desc_hk": "【程度】程度極深。", "example": "A: 宿題終わった？(作业做完了吗)\nB: 課題の量がエグい。(作业量太离谱了)", "example_tw": "A: 宿題終わった？(作業做完了嗎)\nB: 課題の量がエグい。(作業量太離譜了)", "example_hk": "A: 宿題終わった？(做完功課未)\nB: 課題の量がエグい。(功課量好癲)", "tags": ["SLANG", "EMOTION"], "stars": 2 },
  { "id": "l09", "cat": "LIFE", "term": "ウケる", "kana": "うける", "romaji": "Ukeru", "level": 1, "meaning": "笑死 / 有趣", "meaning_tw": "笑死 / 好笑", "meaning_hk": "笑死 / 好正", "desc": "【开心】觉得好笑。", "desc_tw": "【開心】覺得好笑。", "desc_hk": "【開心】覺得好笑。", "example": "A: 変顔見て。(看这鬼脸)\nB: その顔ウケるww(那表情笑死ww)", "example_tw": "A: 変顔見て。(看這鬼臉)\nB: その顔ウケるww(那表情笑死ww)", "example_hk": "A: 変顔見て。(睇下個鬼臉)\nB: その顔ウケるww(個樣笑死ww)", "tags": ["SOCIAL", "EMOTION"], "stars": 2 },
  { "id": "l10", "cat": "LIFE", "term": "草", "kana": "くさ", "romaji": "Kusa", "level": 1, "meaning": "笑死 (www)", "meaning_tw": "笑死 (www)", "meaning_hk": "笑死 (www)", "desc": "【网络】网路用语口语化。", "desc_tw": "【網路】網路用語口語化。", "desc_hk": "【網絡】網絡用語口語化。", "example": "A: 先生が噛んだ。(老师咬舌头了)\nB: それは流石に草。(那是真的草)", "example_tw": "A: 先生が噛んだ。(老師咬舌頭了)\nB: それは流石に草。(那是真的草)", "example_hk": "A: 先生が噛んだ。(阿Sir食螺絲)\nB: それは流石に草。(真係笑死)", "tags": ["SLANG"], "stars": 3 },
  { "id": "l11", "cat": "LIFE", "term": "詰んだ", "kana": "つんだ", "romaji": "Tsunda", "level": 2, "meaning": "完了 / G了", "meaning_tw": "完了 / 沒救了 / GG", "meaning_hk": "玩完 / GG", "desc": "【绝望】无药可救。", "desc_tw": "【絕望】無藥可救。", "desc_hk": "【絕望】無藥可救。", "example": "A: 勉強してない...(没复习...)\nB: テスト詰んだわ。(考试G了)", "example_tw": "A: 勉強してない...(沒複習...)\nB: テスト詰んだわ。(考試G了)", "example_hk": "A: 勉強してない...(無溫書...)\nB: テスト詰んだわ。(測驗GG了)", "tags": ["SLANG", "EMOTION"], "stars": 2 },
  { "id": "l12", "cat": "LIFE", "term": "しんどい", "kana": "しんどい", "romaji": "Shindoi", "level": 2, "meaning": "心累 / 难受", "meaning_tw": "心累 / 難受", "meaning_hk": "好攰 / 辛苦", "desc": "【疲惫】身心俱疲。", "desc_tw": "【疲憊】身心俱疲。", "desc_hk": "【疲憊】身心俱疲。", "example": "A: 仕事終わらない。(工作做不完)\nB: 生きるのがしんどい。(活着真累)", "example_tw": "A: 仕事終わらない。(工作做不完)\nB: 生きるのがしんどい。(活著真累)", "example_hk": "A: 仕事終わらない。(做唔完野)\nB: 生きるのがしんどい。(做人好辛苦)", "tags": ["EMOTION"], "stars": 2 },
  { "id": "l13", "cat": "LIFE", "term": "ダルい", "kana": "だるい", "romaji": "Darui", "level": 1, "meaning": "好烦 / 没劲", "meaning_tw": "好煩 / 懶得動 / 沒勁", "meaning_hk": "好煩 / 頹", "desc": "【厌烦】不想动。", "desc_tw": "【厭煩】不想動。", "desc_hk": "【厭煩】唔想郁。", "example": "A: 出かける？(出门吗)\nB: 風呂入るのダルい。(洗澡好烦)", "example_tw": "A: 出かける？(出門嗎)\nB: 風呂入るのダルい。(洗澡好煩)", "example_hk": "A: 出かける？(出唔出街)\nB: 風呂入るのダルい。(沖涼好煩)", "tags": ["EMOTION"], "stars": 2 },
  { "id": "l14", "cat": "LIFE", "term": "眠い", "kana": "ねむい", "romaji": "Nemui", "level": 1, "meaning": "困", "meaning_tw": "睏 / 想睡", "meaning_hk": "眼訓", "desc": "【状态】想睡觉。", "desc_tw": "【狀態】想睡覺。", "desc_hk": "【狀態】想訓覺。", "example": "A: 起きてる？(醒着吗)\nB: まじで眠い...(困死了...)", "example_tw": "A: 起きてる？(醒著嗎)\nB: まじで眠い...(睏死了...)", "example_hk": "A: 起きてる？(醒咗未)\nB: まじで眠い...(好眼訓...)", "tags": ["EMOTION"], "stars": 3 },
  { "id": "l15", "cat": "LIFE", "term": "尊い", "kana": "とうとい", "romaji": "Toutoi", "level": 3, "meaning": "太尊了 / AWSL", "meaning_tw": "太尊了 / 我沒了 / AWSL", "meaning_hk": "世一 / 尊死", "desc": "【推活】对喜欢角色的最高赞美。", "desc_tw": "【推活】對喜歡角色的最高讚美。", "desc_hk": "【推活】對鍾意角色嘅最高讚美。", "example": "A: 新衣装見た？(看新衣服了吗)\nB: 推しが尊すぎて辛い。(推太尊了我死了)", "example_tw": "A: 新衣装見た？(看新衣服了嗎)\nB: 推しが尊すぎて辛い。(推太尊了我死了)", "example_hk": "A: 新衣装見た？(睇咗新衫未)\nB: 推しが尊すぎて辛い。(我推世一，搞唔掂)", "tags": ["SLANG", "EMOTION"], "stars": 1 },
  { "id": "l16", "cat": "LIFE", "term": "エモい", "kana": "えもい", "romaji": "Emoi", "level": 2, "meaning": "有感觉 / 触动", "meaning_tw": "有Feel / 觸動", "meaning_hk": "有Feel / 正", "desc": "【感性】Emotional。形容氛围好、怀旧。", "desc_tw": "【感性】Emotional。形容氛圍好、懷舊。", "desc_hk": "【感性】Emotional。形容氣氛好、懷舊。", "example": "A: 写真撮ったよ。(拍了照片)\nB: この夕焼け、エモいね。(这夕阳真有感觉)", "example_tw": "A: 写真撮ったよ。(拍了照片)\nB: この夕焼け、エモいね。(這夕陽真有感覺)", "example_hk": "A: 写真撮ったよ。(影咗相)\nB: この夕焼け、エモいね。(個日落好有Feel)", "tags": ["SLANG", "EMOTION"], "stars": 2 },
  { "id": "l17", "cat": "LIFE", "term": "チル", "kana": "ちる", "romaji": "Chiru", "level": 2, "meaning": "放松 / 悠闲", "meaning_tw": "放鬆 / Chill", "meaning_hk": "Chill / 放鬆", "desc": "【状态】Chill。放松下来。", "desc_tw": "【狀態】Chill。放鬆下來。", "desc_hk": "【狀態】Chill。放鬆下。", "example": "A: 今どこ？(在哪)\nB: カフェでチルしてる。(在咖啡厅放松)", "example_tw": "A: 今どこ？(在哪)\nB: カフェでチルしてる。(在咖啡廳Chill)", "example_hk": "A: 今どこ？(邊度)\nB: カフェでチルしてる。(Cafe Chill緊)", "tags": ["SLANG"], "stars": 2 },
  { "id": "l18", "cat": "LIFE", "term": "萎えた", "kana": "なえた", "romaji": "Naeta", "level": 2, "meaning": "萎了 / 没兴致", "meaning_tw": "解High / 冷掉 / 沒興致", "meaning_hk": "頹咗 / 冇Mood", "desc": "【失落】突然不想做了。", "desc_tw": "【失落】突然不想做了。", "desc_hk": "【失落】突然唔想做。", "example": "A: 10連敗...(10连跪...)\nB: 負けすぎて萎えた。(输麻了，萎了)", "example_tw": "A: 10連敗...(10連跪...)\nB: 負けすぎて萎えた。(輸麻了，冷掉了)", "example_hk": "A: 10連敗...(10連敗...)\nB: 負けすぎて萎えた。(輸到頹咗)", "tags": ["EMOTION"], "stars": 1 },
  { "id": "l19", "cat": "LIFE", "term": "ぴえん", "kana": "ぴえん", "romaji": "Pien", "level": 2, "meaning": "呜呜呜", "meaning_tw": "嗚嗚嗚", "meaning_hk": "嗚嗚", "desc": "【卖萌】假哭。", "desc_tw": "【賣萌】假哭。", "desc_hk": "【賣萌】扮喊。", "example": "A: 遅刻した。(迟到了)\nB: アイス売り切れ、ぴえん。(冰淇淋卖光了，呜呜)", "example_tw": "A: 遅刻した。(遲到了)\nB: アイス売り切れ、ぴえん。(冰淇淋賣光了，嗚嗚)", "example_hk": "A: 遅刻した。(遲到了)\nB: アイス売り切れ、ぴえん。(雪糕賣曬，嗚嗚)", "tags": ["SLANG", "EMOTION"], "stars": 1 },
  { "id": "l20", "cat": "LIFE", "term": "無理", "kana": "むり", "romaji": "Muri", "level": 1, "meaning": "不行 / 做不到 / 没救", "meaning_tw": "不行 / 沒辦法 / 沒救", "meaning_hk": "唔得 / 搞唔掂", "desc": "【拒绝/绝望】。", "desc_tw": "【拒絕/絕望】。", "desc_hk": "【拒絕/絕望】。", "example": "A: 5時起きできる？(能5点起吗)\nB: 明日早起きとか無理。(早起绝对不行)", "example_tw": "A: 5時起きできる？(能5點起嗎)\nB: 明日早起きとか無理。(早起絕對不行)", "example_hk": "A: 5時起きできる？(5點起唔起到)\nB: 明日早起きとか無理。(早起絕對唔得)", "tags": ["SOCIAL"], "stars": 3 },
  { "id": "l21", "cat": "LIFE", "term": "ワンチャン", "kana": "わんちゃん", "romaji": "Wanchan", "level": 1, "meaning": "说不定 / 有机会", "meaning_tw": "說不定 / 有機會", "meaning_hk": "有機 / 博下", "desc": "【希望】One Chance。", "desc_tw": "【希望】One Chance。", "desc_hk": "【希望】One Chance。", "example": "A: 間に合う？(来得及吗)\nB: 走ればワンチャン間に合う。(跑的话说不定来得及)", "example_tw": "A: 間に合う？(來得及嗎)\nB: 走ればワンチャン間に合う。(跑的話說不定來得及)", "example_hk": "A: 間に合う？(趕唔趕得切)\nB: 走ればワンチャン間に合う。(跑嘅話博下啦)", "tags": ["SLANG", "SOCIAL"], "stars": 2 },
  { "id": "l22", "cat": "LIFE", "term": "あり", "kana": "あり", "romaji": "Ari", "level": 1, "meaning": "可以 / 不错", "meaning_tw": "可以 / 不錯", "meaning_hk": "得 / OK", "desc": "【肯定】表示这个提议行得通。", "desc_tw": "【肯定】表示這個提議行得通。", "desc_hk": "【肯定】表示個提議行得通。", "example": "A: この服どう？(这衣服咋样)\nB: その服、ありだね。(挺不错的)", "example_tw": "A: この服どう？(這衣服怎樣)\nB: その服、ありだね。(挺不錯的)", "example_hk": "A: この服どう？(件衫點)\nB: その服、ありだね。(幾好喎/得喎)", "tags": ["SOCIAL"], "stars": 3 },
  { "id": "l23", "cat": "LIFE", "term": "なし", "kana": "なし", "romaji": "Nashi", "level": 1, "meaning": "不行 / 没戏", "meaning_tw": "不行 / 沒戲", "meaning_hk": "唔得 / 唔OK", "desc": "【否定】表示这个提议不好。", "desc_tw": "【否定】表示這個提議不好。", "desc_hk": "【否定】表示個提議唔好。", "example": "A: 冗談だよ。(开玩笑的)\nB: 今の発言はなしでしょ。(刚才那话过分了吧)", "example_tw": "A: 冗談だよ。(開玩笑的)\nB: 今の発言はなしでしょ。(剛才那話過分了吧)", "example_hk": "A: 冗談だよ。(講笑咋)\nB: 今の発言はなしでしょ。(頭先個句唔得囉)", "tags": ["SOCIAL"], "stars": 3 },
  { "id": "l24", "cat": "LIFE", "term": "りょ", "kana": "りょ", "romaji": "Ryo", "level": 1, "meaning": "收到 / OK", "meaning_tw": "收到 / OK", "meaning_hk": "收到 / OK", "desc": "【回复】'了解'的缩写。", "desc_tw": "【回覆】'了解'的縮寫。", "desc_hk": "【回覆】'了解'嘅縮寫。", "example": "A: 集合ね。(集合哈)\nB: りょ。(O了)", "example_tw": "A: 集合ね。(集合哈)\nB: りょ。(OK)", "example_hk": "A: 集合ね。(集合啦)\nB: りょ。(收到)", "tags": ["SOCIAL", "SLANG"], "stars": 3 },
  { "id": "l25", "cat": "LIFE", "term": "乙", "kana": "おつ", "romaji": "Otsu", "level": 1, "meaning": "辛苦了 / 88", "meaning_tw": "辛苦了 / 88", "meaning_hk": "辛苦曬 / 88", "desc": "【问候】结束时说。", "desc_tw": "【問候】結束時說。", "desc_hk": "【問候】結束時講。", "example": "A: 先落ちる。(我先下了)\nB: おつ〜またね。(辛苦啦~)", "example_tw": "A: 先落ちる。(我先下了)\nB: おつ〜またね。(辛苦啦~)", "example_hk": "A: 先落ちる。(我落先)\nB: おつ〜またね。(辛苦曬~)", "tags": ["SOCIAL"], "stars": 3 },
  { "id": "l26", "cat": "LIFE", "term": "飛ぶ", "kana": "とぶ", "romaji": "Tobu", "level": 2, "meaning": "鸽了 / 跑路", "meaning_tw": "放鳥 / 落跑", "meaning_hk": "放飛機 / 走佬", "desc": "【逃避】不去打工或聚会。", "desc_tw": "【逃避】不去打工或聚會。", "desc_hk": "【逃避】唔去返工或聚會。", "example": "A: 田中くんは？(田中呢)\nB: バイト飛んだ。(打工翘班了)", "example_tw": "A: 田中くんは？(田中呢)\nB: バイト飛んだ。(打工翹班了)", "example_hk": "A: 田中くんは？(田中呢)\nB: バイト飛んだ。(返工放飛機)", "tags": ["SOCIAL"], "stars": 2 },
  { "id": "l27", "cat": "LIFE", "term": "ドタキャン", "kana": "どたきゃん", "romaji": "Dotakyan", "level": 3, "meaning": "临时鸽", "meaning_tw": "臨時放鳥", "meaning_hk": "臨時放飛機", "desc": "【违约】最后一刻取消。", "desc_tw": "【違約】最後一刻取消。", "desc_hk": "【違約】最後一刻取消。", "example": "A: 怒ってる？(生气了？)\nB: ドタキャンされた、最悪。(被临时鸽了，烦死)", "example_tw": "A: 怒ってる？(生氣了？)\nB: ドタキャンされた、最悪。(被臨時放鳥，煩死)", "example_hk": "A: 怒ってる？(嬲緊？)\nB: ドタキャンされた、最悪。(被人臨時放飛機，煩死)", "tags": ["SOCIAL"], "stars": 2 },
  { "id": "l28", "cat": "LIFE", "term": "かまちょ", "kana": "かまちょ", "romaji": "Kamacho", "level": 3, "meaning": "求关注", "meaning_tw": "討拍 / 求關注", "meaning_hk": "想要人陪 / 刷存在感", "desc": "【性格】想要人陪。", "desc_tw": "【性格】想要人陪。", "desc_hk": "【性格】想要人陪。", "example": "A: 連絡多いね。(联系好频繁啊)\nB: 今かまちょモードだから。(因为现在想求关注)", "example_tw": "A: 連絡多いね。(聯繫好頻繁啊)\nB: 今かまちょモードだから。(因為現在想求關注)", "example_hk": "A: 連絡多いね。(咁多Message嘅)\nB: 今かまちょモードだから。(因為而家想人陪)", "tags": ["LOVE", "SOCIAL"], "stars": 1 },
  { "id": "l29", "cat": "LIFE", "term": "イキる", "kana": "いきる", "romaji": "Ikiru", "level": 2, "meaning": "装X / 耍帅", "meaning_tw": "裝B / 耍帥 / 囂張", "meaning_hk": "扮野 / 囂張", "desc": "【贬义】得意忘形。", "desc_tw": "【貶義】得意忘形。", "desc_hk": "【貶義】得意忘形。", "example": "A: 怪我したの？(受伤了？)\nB: イキって失敗したw(装逼失败了w)", "example_tw": "A: 怪我したの？(受傷了？)\nB: イキって失敗したw(裝逼失敗了w)", "example_hk": "A: 怪我したの？(整親？)\nB: イキって失敗したw(扮野失敗囉w)", "tags": ["SOCIAL"], "stars": 2 },
  { "id": "l30", "cat": "LIFE", "term": "既読スルー", "kana": "きどくするー", "romaji": "Kidoku Suruu", "level": 2, "meaning": "已读不回", "meaning_tw": "已讀不回", "meaning_hk": "已讀不回", "desc": "【社交】LINE已读但不回消息。", "desc_tw": "【社交】LINE已讀但不回訊息。", "desc_hk": "【社交】LINE已讀但唔覆機。", "example": "A: 返信来た？(回了吗)\nB: 好きな人に既読スルーされた。(喜欢的人已读不回)", "example_tw": "A: 返信来た？(回了嗎)\nB: 好きな人に既読スルーされた。(喜歡的人已讀不回)", "example_hk": "A: 返信来た？(覆咗未)\nB: 好きな人に既読スルーされた。(鍾意嘅人已讀不回)", "tags": ["LOVE", "SOCIAL"], "stars": 3 },
  { "id": "l31", "cat": "LIFE", "term": "未読スルー", "kana": "みどくするー", "romaji": "Midoku Suruu", "level": 2, "meaning": "不读不回", "meaning_tw": "不讀不回", "meaning_hk": "不讀不回", "desc": "【社交】故意不点开看。", "desc_tw": "【社交】故意不點開看。", "desc_hk": "【社交】故意唔撳入去睇。", "example": "A: まだ見てない？(还没看？)\nB: 未読スルーはやばい。(不读不回太那啥了)", "example_tw": "A: まだ見てない？(還沒看？)\nB: 未読スルーはやばい。(不讀不回太那個了)", "example_hk": "A: まだ見てない？(仲未睇？)\nB: 未読スルーはやばい。(不讀不回太那個了)", "tags": ["LOVE", "SOCIAL"], "stars": 2 },
  { "id": "l32", "cat": "LIFE", "term": "ブロ解", "kana": "ぶろかい", "romaji": "Burokai", "level": 3, "meaning": "双删", "meaning_tw": "雙刪 (封鎖再解鎖)", "meaning_hk": "Block完解Block", "desc": "【推特】拉黑再解黑，为了互相取关。", "desc_tw": "【Twitter】封鎖再解鎖，為了互相取消關注。", "desc_hk": "【Twitter】封鎖再解鎖，為了互相取消關注。", "example": "A: 繋がってる？(还联系吗)\nB: 元彼をブロ解した。(把前任双删了)", "example_tw": "A: 繋がってる？(還聯繫嗎)\nB: 元彼をブロ解した。(把前任雙刪了)", "example_hk": "A: 繋がってる？(仲有聯絡？)\nB: 元彼をブロ解した。(將前度Block完解Block)", "tags": ["LOVE", "SOCIAL"], "stars": 1 },
  { "id": "l33", "cat": "LIFE", "term": "ラグい", "kana": "らぐい", "romaji": "Lagui", "level": 1, "meaning": "卡了", "meaning_tw": "Lag了 / 延遲", "meaning_hk": "Lag機 / 窒", "desc": "【网络】延迟高。", "desc_tw": "【網路】延遲高。", "desc_hk": "【網絡】延遲高。", "example": "A: 動かない？(不动了？)\nB: 回線ラグすぎ。(网太卡了)", "example_tw": "A: 動かない？(不動了？)\nB: 回線ラグすぎ。(網太卡了)", "example_hk": "A: 動かない？(郁唔到？)\nB: 回線ラグすぎ。(個網勁Lag)", "tags": ["SLANG"], "stars": 3 },
  { "id": "l34", "cat": "LIFE", "term": "落ちた", "kana": "おちた", "romaji": "Ochita", "level": 1, "meaning": "掉线了", "meaning_tw": "斷線 / 閃退", "meaning_hk": "斷線 / 彈Game", "desc": "【网络】游戏闪退或断网。", "desc_tw": "【網路】遊戲閃退或斷網。", "desc_hk": "【網路】遊戲閃退或斷網。", "example": "A: あれ、消えた？(咦，人没了？)\nB: ごめん、鯖落ちた。(抱歉，炸服掉线了)", "example_tw": "A: あれ、消えた？(咦，人沒了？)\nB: ごめん、鯖落ちた。(抱歉，伺服器斷線了)", "example_hk": "A: あれ、消えた？(咦，人無咗？)\nB: ごめん、鯖落ちた。(Sorry，Server斷線)", "tags": ["SLANG"], "stars": 3 },
  { "id": "l35", "cat": "LIFE", "term": "野良", "kana": "のら", "romaji": "Nora", "level": 2, "meaning": "路人", "meaning_tw": "路人", "meaning_hk": "路人", "desc": "【队友】非组排的队友。", "desc_tw": "【隊友】非組隊的隊友。", "desc_hk": "【隊友】非組隊嘅隊友。", "example": "A: ランクどう？(排位怎么样)\nB: 今日の野良は強い。(今天的路人很强)", "example_tw": "A: ランクどう？(排位怎麼樣)\nB: 今日の野良は強い。(今天的路人很強)", "example_hk": "A: ランクどう？(Rank點呀)\nB: 今日の野良は強い。(今日啲路人好勁)", "tags": ["SLANG"], "stars": 2 },
  { "id": "l36", "cat": "LIFE", "term": "地雷", "kana": "じらい", "romaji": "Jirai", "level": 2, "meaning": "坑货", "meaning_tw": "雷包 / 雷", "meaning_hk": "雷 / 伏", "desc": "【队友】很菜或捣乱的人。", "desc_tw": "【隊友】很雷或搗亂的人。", "desc_hk": "【隊友】好雷或者搞事嘅人。", "example": "A: 負けた？(输了？)\nB: 味方に地雷がいる。(队友有个大坑货)", "example_tw": "A: 負けた？(輸了？)\nB: 味方に地雷がいる。(隊友有個大雷包)", "example_hk": "A: 負けた？(輸咗？)\nB: 味方に地雷がいる。(隊友有個大雷)", "tags": ["SLANG"], "stars": 2 },
  { "id": "l37", "cat": "LIFE", "term": "キャリー", "kana": "きゃりー", "romaji": "Kyarii", "level": 1, "meaning": "带飞 / C", "meaning_tw": "Carry / 凱瑞 / 帶飛", "meaning_hk": "Carry / 帶飛", "desc": "【实力】Carry。", "desc_tw": "【實力】Carry。", "desc_hk": "【實力】Carry。", "example": "A: 勝てたね！(赢了！)\nB: キャリーありがとう！(感谢带飞！)", "example_tw": "A: 勝てたね！(贏了！)\nB: キャリーありがとう！(感謝凱瑞！)", "example_hk": "A: 勝てたね！(贏咗！)\nB: キャリーありがとう！(多謝Carry！)", "tags": ["SLANG"], "stars": 3 },
  { "id": "l38", "cat": "LIFE", "term": "姫", "kana": "ひめ", "romaji": "Hime", "level": 2, "meaning": "公主", "meaning_tw": "公主", "meaning_hk": "公主", "desc": "【身份】被众星捧月的女玩家。", "desc_tw": "【身份】被眾星捧月的女玩家。", "desc_hk": "【身份】被眾星捧月嘅女玩家。", "example": "A: あの人たち何？(那群人是啥)\nB: あのグループは姫プがすごい。(那群人捧公主捧得太过了)", "example_tw": "A: あの人たち何？(那群人是啥)\nB: あのグループは姫プがすごい。(那群人捧公主捧得太過了)", "example_hk": "A: あの人たち何？(個班人做咩)\nB: あのグループは姫プがすごい。(個班人捧公主捧得好誇張)", "tags": ["SLANG"], "stars": 1 },
  { "id": "l39", "cat": "LIFE", "term": "囲い", "kana": "かこい", "romaji": "Kakoi", "level": 3, "meaning": "舔狗群 / 骑士团", "meaning_tw": "騎士團 / 護航仔", "meaning_hk": "觀音兵 / 騎士團", "desc": "【群体】围着'公主'转的人。", "desc_tw": "【群體】圍著'公主'轉的人。", "desc_hk": "【群體】圍住'公主'轉嘅人。", "example": "A: 守られてるね。(被保护得很好呢)\nB: 囲いが必死だな。(骑士团在拼命护驾呢)", "example_tw": "A: 守られてるね。(被保護得很好呢)\nB: 囲いが必死だな。(騎士團在拼命護駕呢)", "example_hk": "A: 守られてるね。(被保護得好好呢)\nB: 囲いが必死だな。(成班觀音兵喺度護駕)", "tags": ["SLANG"], "stars": 1 },
  { "id": "l40", "cat": "LIFE", "term": "スマーフ", "kana": "すまーふ", "romaji": "Sumaafu", "level": 2, "meaning": "炸鱼", "meaning_tw": "虐菜 / 開小號", "meaning_hk": "虐菜 / 開細號", "desc": "【行为】开小号虐菜。", "desc_tw": "【行為】開小號虐菜。", "desc_hk": "【行為】開細號虐菜。", "example": "A: 強すぎない？(是不是太强了)\nB: 相手スマーフだろ。(对面是炸鱼的吧)", "example_tw": "A: 強すぎない？(是不是太強了)\nB: 相手スマーフだろ。(對面是虐菜的吧)", "example_hk": "A: 強すぎない？(係咪太勁)\nB: 相手スマーフだろ。(對面虐菜掛)", "tags": ["SLANG"], "stars": 2 },
  { "id": "l41", "cat": "LIFE", "term": "彼氏/彼女", "kana": "かれし/かのじょ", "romaji": "Kareshi/Kanojo", "level": 1, "meaning": "男朋友/女朋友", "meaning_tw": "男朋友/女朋友", "meaning_hk": "男朋友/女朋友", "desc": "对象。", "desc_tw": "對象。", "desc_hk": "對象。", "example": "A: 週末空いてる？(周末有空吗)\nB: 彼女とデート。(要跟女朋友约会)", "example_tw": "A: 週末空いてる？(週末有空嗎)\nB: 彼女とデート。(要跟女朋友約會)", "example_hk": "A: 週末空いてる？(週末得唔得閒)\nB: 彼女とデート。(要同女朋友拍拖)", "tags": ["LOVE"], "stars": 3 },
  { "id": "l42", "cat": "LIFE", "term": "元カレ/元カノ", "kana": "もとかれ/もとかの", "romaji": "Motokare/Motokano", "level": 1, "meaning": "前任", "meaning_tw": "前任 / 前男友 / 前女友", "meaning_hk": "前度 / Ex", "desc": "前男友/前女友。", "desc_tw": "前男友/前女友。", "desc_hk": "前男友/前女友。", "example": "A: 誰から？(谁的电话)\nB: 元カレ。無視でいい。(前男友。不用理)", "example_tw": "A: 誰から？(誰的電話)\nB: 元カレ。無視でいい。(前男友。不用理)", "example_hk": "A: 誰から？(邊個打黎)\nB: 元カレ。無視でいい。(前度。唔駛理)", "tags": ["LOVE"], "stars": 2 },
  { "id": "l43", "cat": "LIFE", "term": "告る", "kana": "こくる", "romaji": "Kokuru", "level": 2, "meaning": "告白", "meaning_tw": "告白", "meaning_hk": "表白", "desc": "表白。", "desc_tw": "告白。", "desc_hk": "表白。", "example": "A: 決心した？(决定了吗)\nB: 明日告るつもり。(打算明天表白)", "example_tw": "A: 決心した？(決定了嗎)\nB: 明日告るつもり。(打算明天告白)", "example_hk": "A: 決心した？(決定咗未)\nB: 明日告るつもり。(打算聽日表白)", "tags": ["LOVE"], "stars": 2 },
  { "id": "l44", "cat": "LIFE", "term": "振られる", "kana": "ふられる", "romaji": "Furareru", "level": 2, "meaning": "被甩/被拒", "meaning_tw": "被甩 / 被拒絕", "meaning_hk": "被拒絕 / 食檸檬", "desc": "失恋。", "desc_tw": "失戀。", "desc_hk": "失戀。", "example": "A: 元気ないね。(没精神啊)\nB: 告って振られた。(表白被拒了)", "example_tw": "A: 元気ないね。(沒精神啊)\nB: 告って振られた。(告白被甩了)", "example_hk": "A: 元気ないね。(無精打采咁)\nB: 告って振られた。(表白食檸檬)", "tags": ["LOVE"], "stars": 2 },
  { "id": "l45", "cat": "LIFE", "term": "モテる", "kana": "もてる", "romaji": "Moteru", "level": 1, "meaning": "受欢迎", "meaning_tw": "受歡迎 / 有人氣", "meaning_hk": "受歡迎 / 有Market", "desc": "有人气。", "desc_tw": "有人氣。", "desc_hk": "有人氣。", "example": "A: 田中くんかっこいい。(田中君好帅)\nB: あいつ絶対モテる。(他绝对很受欢迎)", "example_tw": "A: 田中くんかっこいい。(田中君好帥)\nB: あいつ絶対モテる。(他絕對很受歡迎)", "example_hk": "A: 田中くんかっこいい。(田中同學好靚仔)\nB: あいつ絶対モテる。(佢絕對好受歡迎)", "tags": ["LOVE"], "stars": 2 },
  { "id": "l46", "cat": "LIFE", "term": "推し", "kana": "おし", "romaji": "Oshi", "level": 1, "meaning": "本命/推", "meaning_tw": "本命 / 推", "meaning_hk": "本命 / 推", "desc": "最喜欢的。", "desc_tw": "最喜歡的。", "desc_hk": "最鍾意嘅。", "example": "A: 誰が好き？(喜欢谁)\nB: 推しはジェットです。(我推捷风)", "example_tw": "A: 誰が好き？(喜歡誰)\nB: 推しはジェットです。(我推Jett)", "example_hk": "A: 誰が好き？(鍾意邊個)\nB: 推しはジェットです。(我推Jett)", "tags": ["SOCIAL", "SLANG"], "stars": 3 },
  { "id": "l47", "cat": "LIFE", "term": "リア充", "kana": "りあじゅう", "romaji": "Riajuu", "level": 2, "meaning": "现充", "meaning_tw": "現充", "meaning_hk": "現充", "desc": "生活充实的人。", "desc_tw": "生活充實的人。", "desc_hk": "生活充實嘅人。", "example": "A: クリスマスだね。(圣诞节了)\nB: リア充爆発しろ。(现充都爆炸吧)", "example_tw": "A: クリスマスだね。(聖誕節了)\nB: リア充爆発しろ。(現充都爆炸吧)", "example_hk": "A: クリスマスだね。(聖誕節啦)\nB: リア充爆発しろ。(現充爆炸啦)", "tags": ["SOCIAL"], "stars": 2 },
  { "id": "l48", "cat": "LIFE", "term": "バイト", "kana": "ばいと", "romaji": "Baito", "level": 1, "meaning": "打工/兼职", "meaning_tw": "打工", "meaning_hk": "返工 / 兼職", "desc": "Arbeit。", "desc_tw": "Arbeit。", "desc_hk": "Arbeit。", "example": "A: 遊べる？(能出来玩吗)\nB: 今日バイトだわ。(今天打工)", "example_tw": "A: 遊べる？(能出來玩嗎)\nB: 今日バイトだわ。(今天打工)", "example_hk": "A: 遊べる？(出唔出黎玩)\nB: 今日バイトだわ。(今日要返工)", "tags": ["SCHOOL"], "stars": 3 },
  { "id": "l49", "cat": "LIFE", "term": "サボる", "kana": "さぼる", "romaji": "Saboru", "level": 1, "meaning": "翘课/偷懒", "meaning_tw": "翹課 / 偷懶", "meaning_hk": "走堂 / 蛇王", "desc": "Sabotage。", "desc_tw": "Sabotage。", "desc_hk": "Sabotage。", "example": "A: 授業だるい。(上课好烦)\nB: サボってカラオケ行こ。(翘课去唱K吧)", "example_tw": "A: 授業だるい。(上課好煩)\nB: サボってカラオケ行こ。(翹課去唱K吧)", "example_hk": "A: 授業だるい。(上堂好煩)\nB: サボってカラオケ行こ。(走堂去唱K啦)", "tags": ["SCHOOL"], "stars": 2 },
  { "id": "l50", "cat": "LIFE", "term": "フル単", "kana": "ふるたん", "romaji": "Furutan", "level": 3, "meaning": "满绩/全过", "meaning_tw": "歐趴 / 全過", "meaning_hk": "全部Pass / 過三爆四", "desc": "拿满学分。", "desc_tw": "拿滿學分。", "desc_hk": "拿滿學分。", "example": "A: 成績どう？(成绩怎么样)\nB: 今期フル単いけるかも。(这学期可能全过)", "example_tw": "A: 成績どう？(成績怎麼樣)\nB: 今期フル単いけるかも。(這學期可能歐趴)", "example_hk": "A: 成績どう？(成績點呀)\nB: 今期フル単いけるかも。(今個Sem可能全部Pass)", "tags": ["SCHOOL"], "stars": 2 },
  { "id": "l51", "cat": "LIFE", "term": "落単", "kana": "らくたん", "romaji": "Rakutan", "level": 3, "meaning": "挂科", "meaning_tw": "被當 / 重修", "meaning_hk": "爛Grade / Fail", "desc": "没拿到学分。", "desc_tw": "沒拿到學分。", "desc_hk": "沒拿到學分。", "example": "A: 単位取れた？(拿到学分了吗)\nB: 英語落単した...(英语挂了...)", "example_tw": "A: 単位取れた？(拿到學分了嗎)\nB: 英語落単した...(英語被當了...)", "example_hk": "A: 単位取れた？(攞唔攞到學分)\nB: 英語落単した...(英文Fail咗...)", "tags": ["SCHOOL"], "stars": 2 },
  { "id": "l52", "cat": "LIFE", "term": "奢る", "kana": "おごる", "romaji": "Ogoru", "level": 1, "meaning": "请客", "meaning_tw": "請客", "meaning_hk": "請客 / 萬歲", "desc": "付钱。", "desc_tw": "付錢。", "desc_hk": "比錢。", "example": "A: 財布忘れた。(忘带钱包了)\nB: 今日は俺が奢るよ。(今天我请)", "example_tw": "A: 財布忘れた。(忘記帶錢包了)\nB: 今日は俺が奢るよ。(今天我請)", "example_hk": "A: 財布忘れた。(唔記得帶銀包)\nB: 今日は俺が奢るよ。(今日我請啦)", "tags": ["SOCIAL"], "stars": 3 },
  { "id": "l53", "cat": "LIFE", "term": "金欠", "kana": "きんけつ", "romaji": "Kinketsu", "level": 2, "meaning": "没钱/吃土", "meaning_tw": "吃土 / 沒錢", "meaning_hk": "窮 / 食穀種", "desc": "缺钱。", "desc_tw": "缺錢。", "desc_hk": "缺錢。", "example": "A: 飲み行く？(去喝一杯吗)\nB: 今月まじ金欠。(这个月真吃土了)", "example_tw": "A: 飲み行く？(去喝一杯嗎)\nB: 今月まじ金欠。(這個月真吃土了)", "example_hk": "A: 飲み行く？(去唔去飲野)\nB: 今月まじ金欠。(呢個月真係窮到燶)", "tags": ["SOCIAL"], "stars": 2 },
  { "id": "l59", "cat": "LIFE", "term": "神", "kana": "かみ", "romaji": "Kami", "level": 1, "meaning": "神/太强了", "meaning_tw": "神 / 太強了", "meaning_hk": "神 / 世一", "desc": "赞美。", "desc_tw": "讚美。", "desc_hk": "讚美。", "example": "A: 課題やったよ。(帮你写作业了)\nB: 助かった、まじ神。(帮大忙了，你是神)", "example_tw": "A: 課題やったよ。(幫你寫作業了)\nB: 助かった、まじ神。(幫大忙了，你是神)", "example_hk": "A: 課題やったよ。(幫你做咗功課)\nB: 助かった、まじ神。(幫大忙，你真係神)", "tags": ["SOCIAL", "SLANG"], "stars": 3 },
  { "id": "l60", "cat": "LIFE", "term": "バズる", "kana": "ばずる", "romaji": "Bazuru", "level": 2, "meaning": "火了/上热搜", "meaning_tw": "爆紅 / 上熱搜", "meaning_hk": "上熱門 / Hit爆", "desc": "Buzz。", "desc_tw": "Buzz。", "desc_hk": "Buzz。", "example": "A: 見てこれ。(看这个)\nB: ツイートがバズってる！(推特火了啊！)", "example_tw": "A: 見てこれ。(看這個)\nB: ツイートがバズってる！(推特爆紅了啊！)", "example_hk": "A: 見てこれ。(睇下呢個)\nB: ツイートがバズってる！(推特Hit爆啊！)", "tags": ["SOCIAL", "SLANG"], "stars": 2 },

  // ================= VALORANT (瓦罗兰特 / 特戰英豪 / Valorant) =================
  { "id": "v01", "cat": "VALORANT", "term": "激ロー", "kana": "げきろー", "romaji": "Geki-row", "level": 1, "meaning": "大残", "meaning_tw": "大殘 / 殘血", "meaning_hk": "殘血 / 一絲", "desc": "敌人一丝血。", "desc_tw": "敵人一絲血。", "desc_hk": "敵人一絲血。", "example": "A: 赤箱裏！(红箱后！)\nB: ジェット激ロー！(捷风大残！)", "example_tw": "A: 赤箱裏！(紅箱後！)\nB: ジェット激ロー！(Jett殘血！)", "example_hk": "A: 赤箱裏！(紅箱後！)\nB: ジェット激ロー！(Jett殘血！)", "tags": ["CALLOUT", "COMBAT"], "stars": 3 },
  { "id": "v02", "cat": "VALORANT", "term": "解除中", "kana": "かいじょちゅう", "romaji": "Kaijo Chuu", "level": 1, "meaning": "正在拆包", "meaning_tw": "拆包中", "meaning_hk": "解緊 / 拆緊", "desc": "Defusing。", "desc_tw": "Defusing。", "desc_hk": "Defusing。", "example": "A: 解除中！カバー！(正在拆！帮我架枪！)\nB: OK！(OK！)", "example_tw": "A: 解除中！カバー！(正在拆！幫我架槍！)\nB: OK！(OK！)", "example_hk": "A: 解除中！カバー！(拆緊！幫我架槍！)\nB: OK！(OK！)", "tags": ["TACTIC", "COMBAT"], "stars": 3 },
  { "id": "v03", "cat": "VALORANT", "term": "ガチ解除", "kana": "がちかいじょ", "romaji": "Gachi Kaijo", "level": 3, "meaning": "强拆", "meaning_tw": "強拆", "meaning_hk": "強拆", "desc": "Stick it。", "desc_tw": "Stick it。", "desc_hk": "Stick it。", "example": "A: 足音する。(有脚步)\nB: ガチ解除！通す！(强拆！直接拆到底！)", "example_tw": "A: 足音する。(有腳步)\nB: ガチ解除！通す！(強拆！直接拆到底！)", "example_hk": "A: 足音する。(有腳步)\nB: ガチ解除！通す！(強拆！直接拆到底！)", "tags": ["TACTIC", "COMBAT"], "stars": 2 },
  { "id": "v04", "cat": "VALORANT", "term": "設置", "kana": "せっち", "romaji": "Secchi", "level": 1, "meaning": "下包", "meaning_tw": "裝包 / 下包", "meaning_hk": "落包", "desc": "Plant。", "desc_tw": "Plant。", "desc_hk": "Plant。", "example": "A: サイトクリア。(包点没人)\nB: Aに設置する。(下A包)", "example_tw": "A: サイトクリア。(包點沒人)\nB: Aに設置する。(裝A包)", "example_hk": "A: サイトクリア。(Site沒人)\nB: Aに設置する。(落A包)", "tags": ["TACTIC", "SYSTEM"], "stars": 3 },
  { "id": "v05", "cat": "VALORANT", "term": "スパイク", "kana": "すぱいく", "romaji": "Supaiku", "level": 1, "meaning": "爆能器 / 包", "meaning_tw": "輻能核心 / 包", "meaning_hk": "Spike / 包", "desc": "Spike。", "desc_tw": "Spike。", "desc_hk": "Spike。", "example": "A: スパイク落ちてる。(包掉了)\nB: 拾うわ。(我捡)", "example_tw": "A: スパイク落ちてる。(包掉了)\nB: 拾うわ。(我撿)", "example_hk": "A: スパイク落ちてる。(包跌咗)\nB: 拾うわ。(我執)", "tags": ["SYSTEM", "TACTIC"], "stars": 3 },
  { "id": "v06", "cat": "VALORANT", "term": "エントリー", "kana": "えんとりー", "romaji": "Entorii", "level": 1, "meaning": "进点", "meaning_tw": "進點", "meaning_hk": "Entry / 入點", "desc": "Entry。", "desc_tw": "Entry。", "desc_hk": "Entry。", "example": "A: エントリー行くよ。(我进点了)\nB: スモーク入れる。(我封烟)", "example_tw": "A: エントリー行くよ。(我進點了)\nB: スモーク入れる。(我封煙)", "example_hk": "A: エントリー行くよ。(我Entry)\nB: スモーク入れる。(我封煙)", "tags": ["TACTIC"], "stars": 3 },
  { "id": "v07", "cat": "VALORANT", "term": "リテイク", "kana": "りていく", "romaji": "Riteiku", "level": 2, "meaning": "回防", "meaning_tw": "回防", "meaning_hk": "Retake / 回防", "desc": "Retake。", "desc_tw": "Retake。", "desc_hk": "Retake。", "example": "A: 設置された。(下包了)\nB: 味方待ってリテイク。(等队友回防)", "example_tw": "A: 設置された。(被裝包了)\nB: 味方待ってリテイク。(等隊友回防)", "example_hk": "A: 設置された。(落咗包)\nB: 味方待ってリテイク。(等隊友Retake)", "tags": ["TACTIC"], "stars": 2 },
  { "id": "v08", "cat": "VALORANT", "term": "ローテ", "kana": "ろーて", "romaji": "Roote", "level": 2, "meaning": "转点", "meaning_tw": "轉點", "meaning_hk": "轉點 / Rotate", "desc": "Rotate。", "desc_tw": "Rotate。", "desc_hk": "Rotate。", "example": "A: ここ無理。(这里打不进去)\nB: Bローテしよう。(转B吧)", "example_tw": "A: ここ無理。(這裡打不進去)\nB: Bローテしよう。(轉B吧)", "example_hk": "A: ここ無理。(呢度入唔到)\nB: Bローテしよう。(轉B啦)", "tags": ["TACTIC"], "stars": 2 },
  { "id": "v09", "cat": "VALORANT", "term": "ラッシュ", "kana": "らっしゅ", "romaji": "Rasshu", "level": 1, "meaning": "RUSH / 冲", "meaning_tw": "RUSH / 衝", "meaning_hk": "Rush / 衝", "desc": "Rush。", "desc_tw": "Rush。", "desc_hk": "Rush。", "example": "A: 足音多数！(好多脚步！)\nB: Aラッシュ止められない。(A点RUSH挡不住了)", "example_tw": "A: 足音多数！(好多腳步！)\nB: Aラッシュ止められない。(A RUSH擋不住了)", "example_hk": "A: 足音多数！(好多腳步！)\nB: Aラッシュ止められない。(A Rush擋唔住)", "tags": ["TACTIC"], "stars": 3 },
  { "id": "v10", "cat": "VALORANT", "term": "キープ", "kana": "きーぷ", "romaji": "Kiipu", "level": 1, "meaning": "保枪", "meaning_tw": "保槍", "meaning_hk": "Save / 保槍", "desc": "Save。", "desc_tw": "Save。", "desc_hk": "Save。", "example": "A: 1対4だ。(1打4)\nB: これキープでいい。(这把保枪吧)", "example_tw": "A: 1対4だ。(1打4)\nB: これキープでいい。(這把保槍吧)", "example_hk": "A: 1対4だ。(1打4)\nB: これキープでいい。(呢鋪Save啦)", "tags": ["ECON", "TACTIC"], "stars": 3 },
  { "id": "v11", "cat": "VALORANT", "term": "エコ", "kana": "えこ", "romaji": "Eko", "level": 1, "meaning": "E一把", "meaning_tw": "Eco / 存錢", "meaning_hk": "Eco / 慳錢", "desc": "Eco round。", "desc_tw": "Eco round。", "desc_hk": "Eco round。", "example": "A: お金ない。(没钱)\nB: 今回エコね。(这把E)", "example_tw": "A: お金ない。(沒錢)\nB: 今回エコね。(這把Eco)", "example_hk": "A: お金ない。(無錢)\nB: 今回エコね。(呢鋪Eco)", "tags": ["ECON"], "stars": 3 },
  { "id": "v12", "cat": "VALORANT", "term": "フルバイ", "kana": "ふるばい", "romaji": "Furubai", "level": 1, "meaning": "全起", "meaning_tw": "全買 / Full Buy", "meaning_hk": "Full Buy / 買盡", "desc": "Full buy。", "desc_tw": "Full buy。", "desc_hk": "Full buy。", "example": "A: お金ある？(有钱吗)\nB: 次フルバイいける。(下把能全起)", "example_tw": "A: お金ある？(有錢嗎)\nB: 次フルバイいける。(下把能全買)", "example_hk": "A: お金ある？(有錢嗎)\nB: 次フルバイいける。(下鋪可以Full Buy)", "tags": ["ECON"], "stars": 3 },
  { "id": "v13", "cat": "VALORANT", "term": "ハーフ", "kana": "はーふ", "romaji": "Haafu", "level": 2, "meaning": "拆了一半", "meaning_tw": "拆了一半 / 過半", "meaning_hk": "一半 / Half", "desc": "Half defused。", "desc_tw": "Half defused。", "desc_hk": "Half defused。", "example": "A: 解除どう？(拆得怎么样？)\nB: ハーフいった！(过半了！)", "example_tw": "A: 解除どう？(拆得怎麼樣？)\nB: ハーフいった！(過半了！)", "example_hk": "A: 解除どう？(拆成點？)\nB: ハーフいった！(過半了！)", "tags": ["TACTIC", "COMBAT"], "stars": 2 },
  { "id": "v14", "cat": "VALORANT", "term": "足音", "kana": "あしおと", "romaji": "Ashioto", "level": 1, "meaning": "脚步声", "meaning_tw": "腳步聲", "meaning_hk": "腳步聲", "desc": "Footsteps。", "desc_tw": "Footsteps。", "desc_hk": "Footsteps。", "example": "A: Bどう？(B点情况？)\nB: 足音複数！(好几个脚步声！)", "example_tw": "A: Bどう？(B點情況？)\nB: 足音複数！(好幾個腳步聲！)", "example_hk": "A: Bどう？(B點點呀？)\nB: 足音複数！(好多腳步聲！)", "tags": ["CALLOUT", "COMBAT"], "stars": 3 },
  { "id": "v15", "cat": "VALORANT", "term": "裏取り", "kana": "うらどり", "romaji": "Uradori", "level": 2, "meaning": "绕后", "meaning_tw": "繞背 / 繞後", "meaning_hk": "兜後 / 繞後", "desc": "Flanking。", "desc_tw": "Flanking。", "desc_hk": "Flanking。", "example": "A: 敵見えない。(看不到人)\nB: 裏取り警戒して。(小心绕后)", "example_tw": "A: 敵見えない。(看不到人)\nB: 裏取り警戒して。(小心繞背)", "example_hk": "A: 敵見えない。(見唔到人)\nB: 裏取り警戒して。(小心兜後)", "tags": ["TACTIC", "COMBAT"], "stars": 2 },
  { "id": "v16", "cat": "VALORANT", "term": "ピーク", "kana": "ぴーく", "romaji": "Piiku", "level": 2, "meaning": "拉出去 / 对枪", "meaning_tw": "Peek / 拉出去", "meaning_hk": "Peek / 裝", "desc": "Peek。", "desc_tw": "Peek。", "desc_hk": "Peek。", "example": "A: 敵いる？(有人吗)\nB: ドライでピークしないで。(别干拉)", "example_tw": "A: 敵いる？(有人嗎)\nB: ドライでピークしないで。(別乾拉)", "example_hk": "A: 敵いる？(有人嗎)\nB: ドライでピークしないで。(唔好乾拉/Peek)", "tags": ["COMBAT", "TACTIC"], "stars": 2 },
  { "id": "v17", "cat": "VALORANT", "term": "クリアリング", "kana": "くりありんぐ", "romaji": "Kuriaringu", "level": 3, "meaning": "搜点", "meaning_tw": "搜點", "meaning_hk": "搜點 / Clear點", "desc": "Clearing corners。", "desc_tw": "Clearing corners。", "desc_hk": "Clearing corners。", "example": "A: 敵いた！(有人！)\nB: ちゃんとクリアリングして。(好好搜点啊)", "example_tw": "A: 敵いた！(有人！)\nB: ちゃんとクリアリングして。(好好搜點啊)", "example_hk": "A: 敵いた！(有人！)\nB: ちゃんとクリアリングして。(Check清楚啲位啦)", "tags": ["TACTIC"], "stars": 2 },
  { "id": "v18", "cat": "VALORANT", "term": "ワンピック", "kana": "わんぴっく", "romaji": "Wanpikku", "level": 2, "meaning": "掉一个 / 抓单", "meaning_tw": "抓掉一個 / 抓單", "meaning_hk": "抓單 / 捉一個", "desc": "One pick。", "desc_tw": "One pick。", "desc_hk": "One pick。", "example": "A: 状況は？(情况？)\nB: ミッドでワンピック取った。(中路抓了一个)", "example_tw": "A: 状況は？(情況？)\nB: ミッドでワンピック取った。(中路抓了一個)", "example_hk": "A: 状況は？(情況？)\nB: ミッドでワンピック取った。(中路捉咗一個)", "tags": ["COMBAT", "CALLOUT"], "stars": 2 },
  { "id": "v19", "cat": "VALORANT", "term": "フィジカル", "kana": "ふぃじかる", "romaji": "Fijikaru", "level": 3, "meaning": "枪法硬", "meaning_tw": "槍法硬 / 槍硬", "meaning_hk": "槍硬", "desc": "Physical。", "desc_tw": "Physical。", "desc_hk": "Physical。", "example": "A: 撃ち勝った！(对赢了！)\nB: フィジカルで解決した。(靠枪法硬解了)", "example_tw": "A: 撃ち勝った！(對贏了！)\nB: フィジカルで解決した。(靠槍法硬解了)", "example_hk": "A: 撃ち勝った！(對贏咗！)\nB: フィジカルで解決した。(靠槍硬打贏)", "tags": ["COMBAT"], "stars": 2 },
  { "id": "v20", "cat": "VALORANT", "term": "クラッチ", "kana": "くらっち", "romaji": "Kuracchi", "level": 2, "meaning": "残局获胜", "meaning_tw": "Clutch / 殘局獲勝", "meaning_hk": "Clutch / 殘局", "desc": "Clutch。", "desc_tw": "Clutch。", "desc_hk": "Clutch。", "example": "A: 勝った！(赢了！)\nB: ナイスクラッチ！(残局打得好！)", "example_tw": "A: 勝った！(贏了！)\nB: ナイスクラッチ！(殘局打得好！)", "example_hk": "A: 勝った！(贏咗！)\nB: ナイスクラッチ！(Nice Clutch！)", "tags": ["COMBAT", "CALLOUT"], "stars": 2 },
  { "id": "v21", "cat": "VALORANT", "term": "ヘヴン", "kana": "へゔん", "romaji": "Hevun", "level": 2, "meaning": "二楼/天堂", "meaning_tw": "二樓 / 天堂", "meaning_hk": "Heaven / 二樓", "desc": "Heaven。", "desc_tw": "Heaven。", "desc_hk": "Heaven。", "example": "A: 敵どこ？(人在哪)\nB: ヘヴンにスモーク。(在二楼，给烟)", "example_tw": "A: 敵どこ？(人在哪)\nB: ヘヴンにスモーク。(在二樓，給煙)", "example_hk": "A: 敵どこ？(人係邊)\nB: ヘヴンにスモーク。(Heaven比煙)", "tags": ["CALLOUT"], "stars": 2 },
  { "id": "v22", "cat": "VALORANT", "term": "ヘル", "kana": "へる", "romaji": "Heru", "level": 2, "meaning": "楼下/地狱", "meaning_tw": "樓下 / 地獄", "meaning_hk": "Hell / 樓下", "desc": "Hell。", "desc_tw": "Hell。", "desc_hk": "Hell。", "example": "A: サイト入るよ。(进点了)\nB: ヘルに隠れてる。(躲在楼下)", "example_tw": "A: サイト入るよ。(進點了)\nB: ヘルに隠れてる。(躲在樓下)", "example_hk": "A: サイト入るよ。(入Site了)\nB: ヘルに隠れてる。(匿係Hell)", "tags": ["CALLOUT"], "stars": 2 },
  { "id": "v23", "cat": "VALORANT", "term": "ミッド", "kana": "みっど", "romaji": "Middo", "level": 1, "meaning": "中路", "meaning_tw": "中路 / Mid", "meaning_hk": "Mid / 中路", "desc": "Mid。", "desc_tw": "Mid。", "desc_hk": "Mid。", "example": "A: どこ行く？(去哪)\nB: ミッド進行。(打中路)", "example_tw": "A: どこ行く？(去哪)\nB: ミッド進行。(打中路)", "example_hk": "A: どこ行く？(去邊)\nB: ミッド進行。(打Mid)", "tags": ["CALLOUT"], "stars": 3 },
  { "id": "v24", "cat": "VALORANT", "term": "ショート", "kana": "しょーと", "romaji": "Shooto", "level": 1, "meaning": "小道", "meaning_tw": "小道 / Short", "meaning_hk": "Short / 細道", "desc": "Short。", "desc_tw": "Short。", "desc_hk": "Short。", "example": "A: 足音した。(有脚步)\nB: Aショート来るかも。(可能来A小)", "example_tw": "A: 足音した。(有腳步)\nB: Aショート来るかも。(可能來A小)", "example_hk": "A: 足音した。(有腳步)\nB: Aショート来るかも。(可能黎A Short)", "tags": ["CALLOUT"], "stars": 3 },
  { "id": "v25", "cat": "VALORANT", "term": "ロング", "kana": "ろんぐ", "romaji": "Rongu", "level": 1, "meaning": "大路/长廊", "meaning_tw": "大路 / Long", "meaning_hk": "Long / 大道", "desc": "Long。", "desc_tw": "Long。", "desc_hk": "Long。", "example": "A: C行く？(去C吗)\nB: Cロングにオペ。(C大有大狙)", "example_tw": "A: C行く？(去C嗎)\nB: Cロングにオペ。(C大有大狙)", "example_hk": "A: C行く？(去C嗎)\nB: Cロングにオペ。(C Long有OP)", "tags": ["CALLOUT"], "stars": 3 },
  { "id": "v26", "cat": "VALORANT", "term": "サイト", "kana": "さいと", "romaji": "Saito", "level": 1, "meaning": "包点", "meaning_tw": "點 / Site", "meaning_hk": "Site / 點", "desc": "Site。", "desc_tw": "Site。", "desc_hk": "Site。", "example": "A: 設置できる？(能下包吗)\nB: サイト裏確認して。(看一下包点后面)", "example_tw": "A: 設置できる？(能下包嗎)\nB: サイト裏確認して。(看一下點後)", "example_hk": "A: 設置できる？(落唔落到包)\nB: サイト裏確認して。(Check下Site後)", "tags": ["CALLOUT", "SYSTEM"], "stars": 3 },
  { "id": "v27", "cat": "VALORANT", "term": "メイン", "kana": "めいん", "romaji": "Mein", "level": 1, "meaning": "主路/大厅", "meaning_tw": "大廳 / Main", "meaning_hk": "Main / 大廳", "desc": "Main。", "desc_tw": "Main。", "desc_hk": "Main。", "example": "A: 敵見えた？(看到了吗)\nB: Bメイン進行中。(B大厅进人了)", "example_tw": "A: 敵見えた？(看到了嗎)\nB: Bメイン進行中。(B大廳進人了)", "example_hk": "A: 敵見えた？(見唔見到)\nB: Bメイン進行中。(B Main進緊人)", "tags": ["CALLOUT"], "stars": 3 },
  { "id": "v28", "cat": "VALORANT", "term": "CT", "kana": "しーてぃー", "romaji": "Shiitii", "level": 2, "meaning": "警家", "meaning_tw": "防守方重生點 / CT", "meaning_hk": "CT / 防守方Spawn", "desc": "CT Spawn。", "desc_tw": "CT Spawn。", "desc_hk": "CT Spawn。", "example": "A: どこから？(从哪来)\nB: CTから回る。(走警家绕)", "example_tw": "A: どこから？(從哪來)\nB: CTから回る。(走CT繞)", "example_hk": "A: どこから？(邊度黎)\nB: CTから回る。(行CT繞)", "tags": ["CALLOUT"], "stars": 2 },
  { "id": "v29", "cat": "VALORANT", "term": "Tベース", "kana": "てぃーべーす", "romaji": "Tii Beesu", "level": 2, "meaning": "匪家", "meaning_tw": "攻擊方重生點 / T Base", "meaning_hk": "T Base / 攻擊方Spawn", "desc": "T Spawn。", "desc_tw": "T Spawn。", "desc_hk": "T Spawn。", "example": "A: 敵いない。(没人)\nB: Tベースで待つ。(在匪家等)", "example_tw": "A: 敵いない。(沒人)\nB: Tベースで待つ。(在T Base等)", "example_hk": "A: 敵いない。(沒人)\nB: Tベースで待つ。(係T Base等)", "tags": ["CALLOUT"], "stars": 2 },
  { "id": "v30", "cat": "VALORANT", "term": "エルボー", "kana": "えるぼー", "romaji": "Eruboo", "level": 2, "meaning": "肘部/拐角", "meaning_tw": "轉角 / Elbow", "meaning_hk": "Elbow / 轉角", "desc": "Elbow。", "desc_tw": "Elbow。", "desc_hk": "Elbow。", "example": "A: クリア。(没人)\nB: エルボー注意。(小心拐角)", "example_tw": "A: クリア。(沒人)\nB: エルボー注意。(小心轉角)", "example_hk": "A: クリア。(沒人)\nB: エルボー注意。(小心Elbow)", "tags": ["CALLOUT"], "stars": 2 },
  { "id": "v31", "cat": "VALORANT", "term": "ランプ", "kana": "らんぷ", "romaji": "Ranpu", "level": 2, "meaning": "斜坡/灯笼", "meaning_tw": "斜坡 / U-Hall", "meaning_hk": "Lamp / 斜坡", "desc": "Lamps/U-Hall。", "desc_tw": "Lamps/U-Hall。", "desc_hk": "Lamps/U-Hall。", "example": "A: 位置わかる？(知道位置吗)\nB: ランプの中。(在灯笼房里)", "example_tw": "A: 位置わかる？(知道位置嗎)\nB: ランプの中。(在U-Hall裡面)", "example_hk": "A: 位置わかる？(知唔知位置)\nB: ランプの中。(係Lamp入面)", "tags": ["CALLOUT"], "stars": 2 },
  { "id": "v32", "cat": "VALORANT", "term": "フッカー", "kana": "ふっかー", "romaji": "Fukkaa", "level": 3, "meaning": "窗口/Hookah", "meaning_tw": "Hookah / 窗口", "meaning_hk": "Hookah / 窗口", "desc": "Hookah (Bind地图)。", "desc_tw": "Hookah (Bind地圖)。", "desc_hk": "Hookah (Bind地圖)。", "example": "A: グレ入れる。(扔雷)\nB: フッカーに二人。(窗口有两个)", "example_tw": "A: グレ入れる。(丟雷)\nB: フッカーに二人。(窗口有兩個)", "example_hk": "A: グレ入れる。(掉雷)\nB: フッカーに二人。(Hookah有兩個)", "tags": ["CALLOUT"], "stars": 2 },
  { "id": "v33", "cat": "VALORANT", "term": "シャワー", "kana": "しゃわー", "romaji": "Shawaa", "level": 2, "meaning": "浴室", "meaning_tw": "浴室 / Showers", "meaning_hk": "Shower / 浴室", "desc": "Showers (Bind地图)。", "desc_tw": "Showers (Bind地圖)。", "desc_hk": "Showers (Bind地圖)。", "example": "A: 攻め方どうする？(怎么打)\nB: シャワー取ろう。(抢浴室吧)", "example_tw": "A: 攻め方どうする？(怎麼打)\nB: シャワー取ろう。(搶浴室吧)", "example_hk": "A: 攻め方どうする？(點打)\nB: シャワー取ろう。(搶Shower啦)", "tags": ["CALLOUT"], "stars": 2 },
  { "id": "v34", "cat": "VALORANT", "term": "ヴァンダル", "kana": "ゔぁんだる", "romaji": "Vandaru", "level": 1, "meaning": "狂徒", "meaning_tw": "暴徒", "meaning_hk": "Vandal / 暴徒", "desc": "Vandal。", "desc_tw": "Vandal。", "desc_hk": "Vandal。", "example": "A: 武器何買う？(买什么)\nB: ヴァンダル欲しい。(想要狂徒)", "example_tw": "A: 武器何買う？(買什麼)\nB: ヴァンダル欲しい。(想要暴徒)", "example_hk": "A: 武器何買う？(買咩槍)\nB: ヴァンダル欲しい。(想要Vandal)", "tags": ["ECON"], "stars": 3 },
  { "id": "v35", "cat": "VALORANT", "term": "ファントム", "kana": "ふぁんとむ", "romaji": "Fantomu", "level": 1, "meaning": "幻象", "meaning_tw": "幻象", "meaning_hk": "Phantom / 幻象", "desc": "Phantom。", "desc_tw": "Phantom。", "desc_hk": "Phantom。", "example": "A: リコイル苦手。(压枪好难)\nB: ファントムの方が好き。(我比较喜欢幻象)", "example_tw": "A: リコイル苦手。(壓槍好難)\nB: ファントムの方が好き。(我比較喜歡幻象)", "example_hk": "A: リコイル苦手。(壓槍好難)\nB: ファントムの方が好き。(我比較鍾意Phantom)", "tags": ["ECON"], "stars": 3 },
  { "id": "v36", "cat": "VALORANT", "term": "オペ", "kana": "おぺ", "romaji": "Ope", "level": 1, "meaning": "大狙", "meaning_tw": "大狙 / 幹員", "meaning_hk": "OP / 大狙", "desc": "Operator。", "desc_tw": "Operator。", "desc_hk": "Operator。", "example": "A: 武器落ちてる。(有枪)\nB: オペ拾った。(捡了把大狙)", "example_tw": "A: 武器落ちてる。(有槍)\nB: オペ拾った。(撿了把大狙)", "example_hk": "A: 武器落ちてる。(有槍)\nB: オペ拾った。(執咗把OP)", "tags": ["ECON", "COMBAT"], "stars": 3 },
  { "id": "v37", "cat": "VALORANT", "term": "シェリフ", "kana": "しぇりふ", "romaji": "Sherifu", "level": 1, "meaning": "正义", "meaning_tw": "警長", "meaning_hk": "Sheriff / 警長", "desc": "Sheriff。", "desc_tw": "Sheriff。", "desc_hk": "Sheriff。", "example": "A: お金ない。(没钱)\nB: エコだからシェリフ。(ECO局买把正义吧)", "example_tw": "A: お金ない。(沒錢)\nB: エコだからシェリフ。(Eco局買把警長吧)", "example_hk": "A: お金ない。(無錢)\nB: エコだからシェリフ。(Eco局買把Sheriff啦)", "tags": ["ECON"], "stars": 3 },
  { "id": "v38", "cat": "VALORANT", "term": "スペクター", "kana": "すぺくたー", "romaji": "Supekutaa", "level": 1, "meaning": "骇灵", "meaning_tw": "惡靈", "meaning_hk": "Spectre / 惡靈", "desc": "Spectre。", "desc_tw": "Spectre。", "desc_hk": "Spectre。", "example": "A: 詰めるよ。(压出去了)\nB: スペクターで走る。(拿骇灵跑打)", "example_tw": "A: 詰めるよ。(壓出去了)\nB: スペクターで走る。(拿惡靈跑打)", "example_hk": "A: 詰めるよ。(壓出去)\nB: スペクターで走る。(拿Spectre跑打)", "tags": ["ECON"], "stars": 2 },
  { "id": "v39", "cat": "VALORANT", "term": "スモーク", "kana": "すもーく", "romaji": "Sumooku", "level": 1, "meaning": "烟", "meaning_tw": "煙", "meaning_hk": "Smoke / 煙", "desc": "Smoke。", "desc_tw": "Smoke。", "desc_hk": "Smoke。", "example": "A: 射線切って。(封一下枪线)\nB: スモーク焚いて。(封个烟)", "example_tw": "A: 射線切って。(封一下槍線)\nB: スモーク焚いて。(封個煙)", "example_hk": "A: 射線切って。(封一下槍線)\nB: スモーク焚いて。(封個Smoke)", "tags": ["SKILL"], "stars": 3 },
  { "id": "v40", "cat": "VALORANT", "term": "フラッシュ", "kana": "ふらっしゅ", "romaji": "Furasshu", "level": 1, "meaning": "闪光", "meaning_tw": "閃光", "meaning_hk": "Flash / 閃", "desc": "Flash。", "desc_tw": "Flash。", "desc_hk": "Flash。", "example": "A: 敵いる！(有人！)\nB: フラッシュ食らった。(被白了)", "example_tw": "A: 敵いる！(有人！)\nB: フラッシュ食らった。(被白了)", "example_hk": "A: 敵いる！(有人！)\nB: フラッシュ食らった。(食咗閃)", "tags": ["SKILL"], "stars": 3 },
  { "id": "v41", "cat": "VALORANT", "term": "ウルト", "kana": "うると", "romaji": "Uruto", "level": 1, "meaning": "大招", "meaning_tw": "大絕", "meaning_hk": "Ult / 大絕", "desc": "Ultimate。", "desc_tw": "Ultimate。", "desc_hk": "Ultimate。", "example": "A: 攻める？(打吗)\nB: ウルト準備完了。(大招好了)", "example_tw": "A: 攻める？(打嗎)\nB: ウルト準備完了。(大絕好了)", "example_hk": "A: 攻める？(打唔打)\nB: ウルト準備完了。(Ult好咗)", "tags": ["SKILL"], "stars": 3 },
  { "id": "v42", "cat": "VALORANT", "term": "ドローン", "kana": "どろーん", "romaji": "Doroon", "level": 1, "meaning": "无人机/猫头鹰", "meaning_tw": "無人機 / 貓頭鷹", "meaning_hk": "Drone / 無人機", "desc": "Drone (Sova)。", "desc_tw": "Drone (Sova)。", "desc_hk": "Drone (Sova)。", "example": "ドローン展開。\n(无人机展开。)", "example_tw": "ドローン展開。\n(無人機展開。)", "example_hk": "ドローン展開。\n(Drone展開。)", "tags": ["SKILL"], "stars": 2 },
  { "id": "v43", "cat": "VALORANT", "term": "タレット", "kana": "たれっと", "romaji": "Taretto", "level": 1, "meaning": "炮台", "meaning_tw": "砲塔", "meaning_hk": "Turret / 炮台", "desc": "Turret (KJ)。", "desc_tw": "Turret (KJ)。", "desc_hk": "Turret (KJ)。", "example": "A: 敵来てる？(来了吗)\nB: タレット反応。(炮台响了)", "example_tw": "A: 敵来てる？(來了嗎)\nB: タレット反応。(砲塔響了)", "example_hk": "A: 敵来てる？(黎緊？)\nB: タレット反応。(Turret響咗)", "tags": ["SKILL"], "stars": 2 },
  { "id": "v44", "cat": "VALORANT", "term": "ジェット", "kana": "じぇっと", "romaji": "Jetto", "level": 1, "meaning": "捷风", "meaning_tw": "捷風", "meaning_hk": "Jett", "desc": "Jett。", "desc_tw": "Jett。", "desc_hk": "Jett。", "example": "A: 敵強い。(对面很强)\nB: 相手のジェットうざい。(对面捷风很烦)", "example_tw": "A: 敵強い。(對面很強)\nB: 相手のジェットうざい。(對面捷風很煩)", "example_hk": "A: 敵強い。(對面好勁)\nB: 相手のジェットうざい。(對面Jett好煩)", "tags": ["SYSTEM"], "stars": 3 },
  { "id": "v45", "cat": "VALORANT", "term": "レイナ", "kana": "れいな", "romaji": "Reina", "level": 1, "meaning": "蕾娜", "meaning_tw": "芮娜", "meaning_hk": "Reyna", "desc": "Reyna。", "desc_tw": "Reyna。", "desc_hk": "Reyna。", "example": "レイナ、フラッシュ入れて！\n(蕾娜，给个闪！)", "example_tw": "レイナ、フラッシュ入れて！\n(芮娜，給個閃！)", "example_hk": "レイナ、フラッシュ入れて！\n(Reyna，比個閃！)", "tags": ["SYSTEM"], "stars": 3 },
  { "id": "v46", "cat": "VALORANT", "term": "オーメン", "kana": "おーめん", "romaji": "Oomen", "level": 1, "meaning": "幽影", "meaning_tw": "歐門", "meaning_hk": "Omen", "desc": "Omen。", "desc_tw": "Omen。", "desc_hk": "Omen。", "example": "オーメン、スモーク頼む。\n(幽影，给个烟。)", "example_tw": "オーメン、スモーク頼む。\n(歐門，給個煙。)", "example_hk": "オーメン、スモーク頼む。\n(Omen，比個煙。)", "tags": ["SYSTEM"], "stars": 3 },
  { "id": "v47", "cat": "VALORANT", "term": "セージ", "kana": "せーじ", "romaji": "Seeji", "level": 1, "meaning": "贤者", "meaning_tw": "聖祈", "meaning_hk": "Sage", "desc": "Sage。", "desc_tw": "Sage。", "desc_hk": "Sage。", "example": "A: 回復ない。(没血了)\nB: セージ回復して。(贤者奶一口)", "example_tw": "A: 回復ない。(沒血了)\nB: セージ回復して。(聖祈奶一口)", "example_hk": "A: 回復ない。(無血)\nB: セージ回復して。(Sage奶一啖)", "tags": ["SYSTEM"], "stars": 3 },
  { "id": "v48", "cat": "VALORANT", "term": "ソーヴァ", "kana": "そーゔぁ", "romaji": "Soova", "level": 1, "meaning": "索瓦", "meaning_tw": "蘇法", "meaning_hk": "Sova", "desc": "Sova。", "desc_tw": "Sova。", "desc_hk": "Sova。", "example": "ソーヴァ、リコン入れて。\n(索瓦，射个探测箭。)", "example_tw": "ソーヴァ、リコン入れて。\n(蘇法，射個探測箭。)", "example_hk": "ソーヴァ、リコン入れて。\n(Sova，射支箭。)", "tags": ["SYSTEM"], "stars": 2 },
  { "id": "v49", "cat": "VALORANT", "term": "キルジョイ", "kana": "きるじょい", "romaji": "Kirujoi", "level": 1, "meaning": "奇乐", "meaning_tw": "愷宙", "meaning_hk": "Killjoy", "desc": "Killjoy。", "desc_tw": "Killjoy。", "desc_hk": "Killjoy。", "example": "キルジョイ、裏見て。\n(奇乐，看屁股。)", "example_tw": "キルジョイ、裏見て。\n(愷宙，看屁股。)", "example_hk": "キルジョイ、裏見て。\n(Killjoy，睇後尾。)", "tags": ["SYSTEM"], "stars": 2 },
  { "id": "v50", "cat": "VALORANT", "term": "チェンバー", "kana": "ちぇんばー", "romaji": "Chenbaa", "level": 1, "meaning": "尚勃勒", "meaning_tw": "錢博爾", "meaning_hk": "Chamber", "desc": "Chamber。", "desc_tw": "Chamber。", "desc_hk": "Chamber。", "example": "チェンバー、オペ外した。\n(尚勃勒大狙空了。)", "example_tw": "チェンバー、オペ外した。\n(錢博爾大狙空了。)", "example_hk": "チェンバー、オペ外した。\n(Chamber支OP射失咗。)", "tags": ["SYSTEM"], "stars": 2 },

  // ================= APEX (APEX) =================
  { "id": "a01", "cat": "APEX", "term": "激ロー", "kana": "げきろー", "romaji": "Geki-row", "level": 1, "meaning": "大残", "meaning_tw": "大殘 / 殘血", "meaning_hk": "殘血", "desc": "一丝血。", "desc_tw": "一絲血。", "desc_hk": "一絲血。", "example": "A: 敵いた！(有人！)\nB: パス激ロー！(机器人大残！)", "example_tw": "A: 敵いた！(有人！)\nB: パス激ロー！(Pathfinder殘血！)", "example_hk": "A: 敵いた！(有人！)\nB: パス激ロー！(Pathfinder殘血！)", "tags": ["CALLOUT", "COMBAT"], "stars": 3 },
  { "id": "a02", "cat": "APEX", "term": "割った", "kana": "わった", "romaji": "Watta", "level": 1, "meaning": "碎甲", "meaning_tw": "碎甲 / 破甲", "meaning_hk": "爆甲 / 碎甲", "desc": "Cracked。", "desc_tw": "Cracked。", "desc_hk": "Cracked。", "example": "A: アーマーどう？(甲怎么样)\nB: ホライゾン割った！(地平线碎甲！)", "example_tw": "A: アーマーどう？(甲怎麼樣)\nB: ホライゾン割った！(Horizon破甲！)", "example_hk": "A: アーマーどう？(甲點呀)\nB: ホライゾン割った！(Horizon爆甲！)", "tags": ["CALLOUT", "COMBAT"], "stars": 3 },
  { "id": "a03", "cat": "APEX", "term": "肉", "kana": "にく", "romaji": "Niku", "level": 1, "meaning": "打肉", "meaning_tw": "打肉 / 沒甲", "meaning_hk": "肉", "desc": "Flesh。", "desc_tw": "Flesh。", "desc_hk": "Flesh。", "example": "A: ダメージ入った？(打中了吗)\nB: 肉50入ってる！(打肉打了50！)", "example_tw": "A: ダメージ入った？(打中了嗎)\nB: 肉50入ってる！(打肉打了50！)", "example_hk": "A: ダメージ入った？(中唔中)\nB: 肉50入ってる！(入肉50！)", "tags": ["CALLOUT", "COMBAT"], "stars": 3 },
  { "id": "a04", "cat": "APEX", "term": "ダウン", "kana": "だうん", "romaji": "Daun", "level": 1, "meaning": "倒地", "meaning_tw": "倒地", "meaning_hk": "訓低 / 倒地", "desc": "Knocked down。", "desc_tw": "Knocked down。", "desc_hk": "Knocked down。", "example": "敵がダウン。\n(敌人倒地了。)", "example_tw": "敵がダウン。\n(敵人倒地了。)", "example_hk": "敵がダウン。\n(敵人倒地。)", "tags": ["CALLOUT", "COMBAT"], "stars": 3 },
  { "id": "a05", "cat": "APEX", "term": "確キル", "kana": "かくきる", "romaji": "Kakukiru", "level": 2, "meaning": "补人", "meaning_tw": "補人 / 確殺", "meaning_hk": "補人 / 確殺", "desc": "Thirst kill。", "desc_tw": "Thirst kill。", "desc_hk": "Thirst kill。", "example": "A: 敵ダウン。(倒一个)\nB: 確キル入れるわ。(我补掉他)", "example_tw": "A: 敵ダウン。(倒一個)\nB: 確キル入れるわ。(我補掉他)", "example_hk": "A: 敵ダウン。(倒一個)\nB: 確キル入れるわ。(我補咗佢)", "tags": ["COMBAT", "OUTCOME"], "stars": 2 },
  { "id": "a06", "cat": "APEX", "term": "別パ", "kana": "べっぱ", "romaji": "Beppa", "level": 1, "meaning": "劝架队", "meaning_tw": "別隊 / 第三方", "meaning_hk": "第三隊 / 別隊", "desc": "Third party。", "desc_tw": "Third party。", "desc_hk": "Third party。", "example": "A: 足音する。(有脚步)\nB: 別パ来た、引こう。(别队来了，撤)", "example_tw": "A: 足音する。(有腳步)\nB: 別パ来た、引こう。(別隊來了，撤)", "example_hk": "A: 足音する。(有腳步)\nB: 別パ来た、引こう。(第隊黎咗，走)", "tags": ["CALLOUT", "COMBAT"], "stars": 3 },
  { "id": "a07", "cat": "APEX", "term": "漁夫", "kana": "ぎょふ", "romaji": "Gyofu", "level": 2, "meaning": "劝架", "meaning_tw": "勸架 / 漁翁得利", "meaning_hk": "勸架 / 漁人得利", "desc": "Third partying。", "desc_tw": "Third partying。", "desc_hk": "Third partying。", "example": "A: 銃声近い。(枪声很近)\nB: 漁夫りに行こう。(去劝架吧)", "example_tw": "A: 銃声近い。(槍聲很近)\nB: 漁夫りに行こう。(去勸架吧)", "example_hk": "A: 銃声近い。(槍聲好近)\nB: 漁夫りに行こう。(去勸架啦)", "tags": ["COMBAT"], "stars": 2 },
  { "id": "a08", "cat": "APEX", "term": "フォーカス", "kana": "ふぉーかす", "romaji": "Fookasu", "level": 2, "meaning": "集火", "meaning_tw": "集火", "meaning_hk": "Focus / 集火", "desc": "Focus。", "desc_tw": "Focus。", "desc_hk": "Focus。", "example": "A: 誰撃つ？(打谁)\nB: ジブフォーカスして。(集火那个胖子)", "example_tw": "A: 誰撃つ？(打誰)\nB: ジブフォーカスして。(集火那個胖子)", "example_hk": "A: 誰撃つ？(打邊個)\nB: ジブフォーカスして。(Focus個肥仔)", "tags": ["COMBAT"], "stars": 2 },
  { "id": "a09", "cat": "APEX", "term": "スイッチ", "kana": "すいっち", "romaji": "Suicchi", "level": 3, "meaning": "换扛", "meaning_tw": "換位 / 換扛", "meaning_hk": "Switch / 換位", "desc": "Switch。换人抗伤害。", "desc_tw": "Switch。換人抗傷害。", "desc_hk": "Switch。換人抗傷害。", "example": "A: 回復する！(我打药！)\nB: 前スイッチして。(前面换人扛一下)", "example_tw": "A: 回復する！(我打藥！)\nB: 前スイッチして。(前面換人扛一下)", "example_hk": "A: 回復する！(我打藥！)\nB: 前スイッチして。(前面Switch一下)", "tags": ["COMBAT", "HELP"], "stars": 2 },
  { "id": "a10", "cat": "APEX", "term": "引く", "kana": "ひく", "romaji": "Hiku", "level": 1, "meaning": "撤退", "meaning_tw": "撤退 / 拉掉", "meaning_hk": "走 / 撤退", "desc": "Back。", "desc_tw": "Back。", "desc_hk": "Back。", "example": "A: 敵多い！(人太多了！)\nB: やばい、引こう。(不妙，撤吧)", "example_tw": "A: 敵多い！(人太多了！)\nB: やばい、引こう。(不妙，撤吧)", "example_hk": "A: 敵多い！(人好多！)\nB: やばい、引こう。(唔得，走吧)", "tags": ["CALLOUT", "COMBAT"], "stars": 3 },
  { "id": "a11", "cat": "APEX", "term": "バッテリー", "kana": "ばってりー", "romaji": "Batterii", "level": 1, "meaning": "大电", "meaning_tw": "大電", "meaning_hk": "大電", "desc": "Battery。", "desc_tw": "Battery。", "desc_hk": "Battery。", "example": "A: 待って。(等一下)\nB: バッテリー巻く。(我打个大电)", "example_tw": "A: 待って。(等一下)\nB: バッテリー巻く。(我打個大電)", "example_hk": "A: 待って。(等陣)\nB: バッテリー巻く。(我打個大電)", "tags": ["LOOT", "HELP"], "stars": 3 },
  { "id": "a12", "cat": "APEX", "term": "セル", "kana": "せる", "romaji": "Seru", "level": 1, "meaning": "小电", "meaning_tw": "小電", "meaning_hk": "細電", "desc": "Cell。", "desc_tw": "Cell。", "desc_hk": "Cell。", "example": "A: 回復ある？(有药吗)\nB: セルない？(有小电吗)", "example_tw": "A: 回復ある？(有藥嗎)\nB: セルない？(有小電嗎)", "example_hk": "A: 回復ある？(有冇藥)\nB: セルない？(有冇細電)", "tags": ["LOOT", "HELP"], "stars": 3 },
  { "id": "a13", "cat": "APEX", "term": "注射器", "kana": "ちゅうしゃき", "romaji": "Chuushaki", "level": 1, "meaning": "注射器", "meaning_tw": "注射器", "meaning_hk": "針 / 注射器", "desc": "Syringe。", "desc_tw": "Syringe。", "desc_hk": "Syringe。", "example": "A: 肉回復欲しい。(想要肉药)\nB: 注射器落とす。(给你注射器)", "example_tw": "A: 肉回復欲しい。(想要肉藥)\nB: 注射器落とす。(給你注射器)", "example_hk": "A: 肉回復欲しい。(想要肉藥)\nB: 注射器落とす。(比支針你)", "tags": ["LOOT", "HELP"], "stars": 2 },
  { "id": "a14", "cat": "APEX", "term": "キット", "kana": "きっと", "romaji": "Kitto", "level": 1, "meaning": "大药包", "meaning_tw": "大補 / 醫療箱", "meaning_hk": "醫療包 / 大補", "desc": "Med kit。", "desc_tw": "Med kit。", "desc_hk": "Med kit。", "example": "A: 体力ミリ。(一丝血)\nB: キットある。(我有大药包)", "example_tw": "A: 体力ミリ。(一絲血)\nB: キットある。(我有醫療箱)", "example_hk": "A: 体力ミリ。(一絲血)\nB: キットある。(我有大補)", "tags": ["LOOT", "HELP"], "stars": 3 },
  { "id": "a15", "cat": "APEX", "term": "フェニキ", "kana": "ふぇにき", "romaji": "Feniki", "level": 2, "meaning": "凤凰", "meaning_tw": "鳳凰", "meaning_hk": "鳳凰", "desc": "Phoenix Kit。", "desc_tw": "Phoenix Kit。", "desc_hk": "Phoenix Kit。", "example": "A: 削られた。(被打残了)\nB: フェニキ巻くわ。(我打个凤凰)", "example_tw": "A: 削られた。(被打殘了)\nB: フェニキ巻くわ。(我打個鳳凰)", "example_hk": "A: 削られた。(被打殘了)\nB: フェニキ巻くわ。(我打個鳳凰)", "tags": ["LOOT"], "stars": 2 },
  { "id": "a16", "cat": "APEX", "term": "アーマー", "kana": "あーまー", "romaji": "Aamaa", "level": 1, "meaning": "护甲", "meaning_tw": "護甲", "meaning_hk": "甲 / 護甲", "desc": "Shield。", "desc_tw": "Shield。", "desc_hk": "Shield。", "example": "A: 進化させて。(帮我升甲)\nB: 赤アーマー着たい。(想穿红甲)", "example_tw": "A: 進化させて。(幫我升甲)\nB: 赤アーマー着たい。(想穿紅甲)", "example_hk": "A: 進化させて。(幫我升甲)\nB: 赤アーマー着たい。(想著紅甲)", "tags": ["LOOT", "SYSTEM"], "stars": 3 },
  { "id": "a17", "cat": "APEX", "term": "金バック", "kana": "きんばっく", "romaji": "Kin Bakku", "level": 1, "meaning": "金包", "meaning_tw": "金包", "meaning_hk": "金包", "desc": "Gold backpack。", "desc_tw": "Gold backpack。", "desc_hk": "Gold backpack。", "example": "A: 誰が持つ？(谁拿？)\nB: ニューキャッスルに金バック。(纽卡斯尔拿金包)", "example_tw": "A: 誰が持つ？(誰拿？)\nB: ニューキャッスルに金バック。(Newcastle拿金包)", "example_hk": "A: 誰が持つ？(邊個拿？)\nB: ニューキャッスルに金バック。(Newcastle拿金包)", "tags": ["LOOT"], "stars": 2 },
  { "id": "a18", "cat": "APEX", "term": "金ノック", "kana": "きんのっく", "romaji": "Kin Nokku", "level": 2, "meaning": "金盾", "meaning_tw": "金盾", "meaning_hk": "金盾", "desc": "Gold knockdown。", "desc_tw": "Gold knockdown。", "desc_hk": "Gold knockdown。", "example": "A: 蘇生できる？(能自救吗)\nB: 金ノック持ってる。(我有金盾)", "example_tw": "A: 蘇生できる？(能自救嗎)\nB: 金ノック持ってる。(我有金盾)", "example_hk": "A: 蘇生できる？(自救唔自救到)\nB: 金ノック持ってる。(我有金盾)", "tags": ["LOOT", "HELP"], "stars": 2 },
  { "id": "a19", "cat": "APEX", "term": "ヘルメット", "kana": "へるめっと", "romaji": "Herumetto", "level": 1, "meaning": "头盔", "meaning_tw": "頭盔", "meaning_hk": "頭盔", "desc": "Helmet。", "desc_tw": "Helmet。", "desc_hk": "Helmet。", "example": "A: 金だよ。(金的哦)\nB: ヘルメット余り。(多了一个头盔)", "example_tw": "A: 金だよ。(金的哦)\nB: ヘルメット余り。(多了一個頭盔)", "example_hk": "A: 金だよ。(金嫁)\nB: ヘルメット余り。(多咗個頭盔)", "tags": ["LOOT"], "stars": 2 },
  { "id": "a20", "cat": "APEX", "term": "アタッチメント", "kana": "あたっちめんと", "romaji": "Atacchimento", "level": 2, "meaning": "配件", "meaning_tw": "配件", "meaning_hk": "配件", "desc": "Attachment。", "desc_tw": "Attachment。", "desc_hk": "Attachment。", "example": "A: 何探してる？(找什么)\nB: アタッチメント探してる。(找配件)", "example_tw": "A: 何探してる？(找什麼)\nB: アタッチメント探してる。(找配件)", "example_hk": "A: 何探してる？(搵緊咩)\nB: アタッチメント探してる。(搵緊配件)", "tags": ["LOOT"], "stars": 2 },
  { "id": "a21", "cat": "APEX", "term": "カクマガ", "kana": "かくまが", "romaji": "Kakumaga", "level": 2, "meaning": "扩容", "meaning_tw": "擴容彈夾", "meaning_hk": "擴容", "desc": "Extended Mag。", "desc_tw": "Extended Mag。", "desc_hk": "Extended Mag。", "example": "A: マガジンない。(没弹夹)\nB: ライトのカクマガ欲しい。(想要轻型扩容)", "example_tw": "A: マガジンない。(沒彈夾)\nB: ライトのカクマガ欲しい。(想要輕型擴容)", "example_hk": "A: マガジンない。(沒彈夾)\nB: ライトのカクマガ欲しい。(想要輕型擴容)", "tags": ["LOOT"], "stars": 3 },
  { "id": "a22", "cat": "APEX", "term": "スコープ", "kana": "すこーぷ", "romaji": "Sukoopu", "level": 1, "meaning": "倍镜", "meaning_tw": "倍鏡", "meaning_hk": "鏡", "desc": "Optic/Scope。", "desc_tw": "Optic/Scope。", "desc_hk": "Optic/Scope。", "example": "A: 見えない。(看不清)\nB: 2倍スコープ。(2倍镜)", "example_tw": "A: 見えない。(看不清)\nB: 2倍スコープ。(2倍鏡)", "example_hk": "A: 見えない。(睇唔清)\nB: 2倍スコープ。(2倍鏡)", "tags": ["LOOT"], "stars": 3 },
  { "id": "a23", "cat": "APEX", "term": "バレル", "kana": "ばれる", "romaji": "Bareru", "level": 1, "meaning": "枪管", "meaning_tw": "槍管", "meaning_hk": "管", "desc": "Barrel stabilizer。", "desc_tw": "Barrel stabilizer。", "desc_hk": "Barrel stabilizer。", "example": "A: 反動すごい。(后坐力好大)\nB: バレルあるよ。(这里有枪管)", "example_tw": "A: 反動すごい。(後坐力好大)\nB: バレルあるよ。(這裡有槍管)", "example_hk": "A: 反動すごい。(後坐力好大)\nB: バレルあるよ。(呢度有管)", "tags": ["LOOT"], "stars": 2 },
  { "id": "a24", "cat": "APEX", "term": "ストック", "kana": "すとっく", "romaji": "Sutokku", "level": 1, "meaning": "枪托", "meaning_tw": "槍托", "meaning_hk": "托", "desc": "Stock。", "desc_tw": "Stock。", "desc_hk": "Stock。", "example": "A: 武器チェン遅い。(切枪好慢)\nB: 紫ストック。(紫枪托)", "example_tw": "A: 武器チェン遅い。(切槍好慢)\nB: 紫ストック。(紫槍托)", "example_hk": "A: 武器チェン遅い。(轉槍好慢)\nB: 紫ストック。(紫托)", "tags": ["LOOT"], "stars": 2 },
  { "id": "a25", "cat": "APEX", "term": "カービン", "kana": "かーびん", "romaji": "Kaabin", "level": 1, "meaning": "R-301", "meaning_tw": "R-301 / 卡賓", "meaning_hk": "R-301", "desc": "R-301 Carbine。", "desc_tw": "R-301 Carbine。", "desc_hk": "R-301 Carbine。", "example": "A: 武器何？(什么枪)\nB: やっぱカービンだね。(还是R301好用)", "example_tw": "A: 武器何？(什麼槍)\nB: やっぱカービンだね。(還是R301好用)", "example_hk": "A: 武器何？(咩槍)\nB: やっぱカービンだね。(都係R301好用)", "tags": ["LOOT"], "stars": 3 },
  { "id": "a26", "cat": "APEX", "term": "フラトラ", "kana": "ふらとら", "romaji": "Furatora", "level": 1, "meaning": "平行", "meaning_tw": "平行", "meaning_hk": "平行 / Flatline", "desc": "Flatline。", "desc_tw": "Flatline。", "desc_hk": "Flatline。", "example": "A: 弾当たらない。(打不中)\nB: フラトラのリコイルむずい。(平行的后坐力好难压)", "example_tw": "A: 弾当たらない。(打不中)\nB: フラトラのリコイルむずい。(平行的後坐力好難壓)", "example_hk": "A: 弾当たらない。(打唔中)\nB: フラトラのリコイルむずい。(Flatline後坐力好難壓)", "tags": ["LOOT"], "stars": 3 },
  { "id": "a27", "cat": "APEX", "term": "ウィングマン", "kana": "うぃんぐまん", "romaji": "Winguman", "level": 1, "meaning": "小帮手", "meaning_tw": "小幫手", "meaning_hk": "輔助手槍 / Wingman", "desc": "Wingman。", "desc_tw": "Wingman。", "desc_hk": "Wingman。", "example": "A: 単発武器？(单发枪？)\nB: ウィングマン当たらん。(小帮手打不中)", "example_tw": "A: 単発武器？(單發槍？)\nB: ウィングマン当たらん。(小幫手打不中)", "example_hk": "A: 単発武器？(單發槍？)\nB: ウィングマン当たらん。(Wingman打唔中)", "tags": ["LOOT"], "stars": 2 },
  { "id": "a28", "cat": "APEX", "term": "ピーキー", "kana": "ぴーきー", "romaji": "Piikii", "level": 1, "meaning": "和平", "meaning_tw": "和平", "meaning_hk": "和平 / PK", "desc": "Peacekeeper。", "desc_tw": "Peacekeeper。", "desc_hk": "Peacekeeper。", "example": "A: 近距離強い？(近战强吗)\nB: ピーキーでワンパン。(和平一枪秒了)", "example_tw": "A: 近距離強い？(近戰強嗎)\nB: ピーキーでワンパン。(和平一槍秒了)", "example_hk": "A: 近距離強い？(近戰勁唔勁)\nB: ピーキーでワンパン。(PK一槍秒咗)", "tags": ["LOOT"], "stars": 2 },
  { "id": "a29", "cat": "APEX", "term": "エバハチ", "kana": "えばはち", "romaji": "Eba Hachi", "level": 2, "meaning": "EVA-8", "meaning_tw": "EVA-8", "meaning_hk": "EVA-8", "desc": "EVA-8 Auto。", "desc_tw": "EVA-8 Auto。", "desc_hk": "EVA-8 Auto。", "example": "A: ショットガン何？(什么喷子)\nB: エバハチ強化された。(EVA-8加强了)", "example_tw": "A: ショットガン何？(什麼散彈)\nB: エバハチ強化された。(EVA-8加強了)", "example_hk": "A: ショットガン何？(咩散彈)\nB: エバハチ強化された。(EVA-8加強咗)", "tags": ["LOOT"], "stars": 2 },
  { "id": "a30", "cat": "APEX", "term": "マスティフ", "kana": "ますてぃふ", "romaji": "Masutifu", "level": 1, "meaning": "敖犬", "meaning_tw": "敖犬", "meaning_hk": "敖犬", "desc": "Mastiff。", "desc_tw": "Mastiff。", "desc_hk": "Mastiff。", "example": "A: ドーム戦。(泡泡战)\nB: マスティフ強い。(敖犬很强)", "example_tw": "A: ドーム戦。(泡泡戰)\nB: マスティフ強い。(敖犬很強)", "example_hk": "A: ドーム戦。(罩戰)\nB: マスティフ強い。(敖犬很強)", "tags": ["LOOT"], "stars": 3 },
  { "id": "a31", "cat": "APEX", "term": "ネメシス", "kana": "ねめしす", "romaji": "Nemeshisu", "level": 1, "meaning": "复仇女神", "meaning_tw": "復仇女神", "meaning_hk": "復仇女神", "desc": "Nemesis。", "desc_tw": "Nemesis。", "desc_hk": "Nemesis。", "example": "A: エネルギー武器。(能量枪)\nB: ネメシス強すぎ。(复仇女神太强了)", "example_tw": "A: エネルギー武器。(能量槍)\nB: ネメシス強すぎ。(復仇女神太強了)", "example_hk": "A: エネルギー武器。(能量槍)\nB: ネメシス強すぎ。(復仇女神太強了)", "tags": ["LOOT"], "stars": 3 },
  { "id": "a32", "cat": "APEX", "term": "ハボック", "kana": "はぼっく", "romaji": "Habokku", "level": 1, "meaning": "哈沃克", "meaning_tw": "哈博克", "meaning_hk": "哈博克 / Havoc", "desc": "Havoc。", "desc_tw": "Havoc。", "desc_hk": "Havoc。", "example": "A: ターボチャージャーある。(有涡轮)\nB: タボチャ付きハボック。(满配哈沃克)", "example_tw": "A: ターボチャージャーある。(有渦輪)\nB: タボチャ付きハボック。(滿配哈博克)", "example_hk": "A: ターボチャージャーある。(有渦輪)\nB: タボチャ付きハボック。(滿配哈博克)", "tags": ["LOOT"], "stars": 2 },
  { "id": "a33", "cat": "APEX", "term": "ボルト", "kana": "ぼると", "romaji": "Boruto", "level": 1, "meaning": "电冲", "meaning_tw": "電能衝鋒槍", "meaning_hk": "電衝 / Volt", "desc": "Volt SMG。", "desc_tw": "Volt SMG。", "desc_hk": "Volt SMG。", "example": "A: SMG何？(什么冲锋枪)\nB: ボルト安定。(电冲很稳)", "example_tw": "A: SMG何？(什麼衝鋒槍)\nB: ボルト安定。(電能衝鋒槍很穩)", "example_hk": "A: SMG何？(咩衝鋒槍)\nB: ボルト安定。(電衝很穩)", "tags": ["LOOT"], "stars": 3 },
  { "id": "a34", "cat": "APEX", "term": "ナイナイ", "kana": "ないない", "romaji": "Nainai", "level": 2, "meaning": "R-99", "meaning_tw": "R-99", "meaning_hk": "R-99", "desc": "R-99 SMG。", "desc_tw": "R-99 SMG。", "desc_hk": "R-99 SMG。", "example": "A: 弾すぐなくなる。(子弹一会就没了)\nB: ナイナイのリロード速い。(R99换弹很快)", "example_tw": "A: 弾すぐなくなる。(子彈一會就沒了)\nB: ナイナイのリロード速い。(R99換彈很快)", "example_hk": "A: 弾すぐなくなる。(子彈好快無)\nB: ナイナイのリロード速い。(R99換彈好快)", "tags": ["LOOT"], "stars": 2 },
  { "id": "a35", "cat": "APEX", "term": "チャーライ", "kana": "ちゃーらい", "romaji": "Chaarai", "level": 2, "meaning": "充能步枪", "meaning_tw": "充能步槍 / 滋崩", "meaning_hk": "差賴 / Charge Rifle", "desc": "Charge Rifle。", "desc_tw": "Charge Rifle。", "desc_hk": "Charge Rifle。", "example": "A: 遠くから撃たれてる。(远处有人打我)\nB: チャーライうざい。(滋崩真烦)", "example_tw": "A: 遠くから撃たれてる。(遠處有人打我)\nB: チャーライうざい。(滋崩真煩)", "example_hk": "A: 遠くから撃たれてる。(遠處有人打我)\nB: チャーライうざい。(差賴好煩)", "tags": ["LOOT"], "stars": 2 },
  { "id": "a36", "cat": "APEX", "term": "クレーバー", "kana": "くれーばー", "romaji": "Kureebaa", "level": 1, "meaning": "克雷贝尔", "meaning_tw": "克雷貝爾", "meaning_hk": "克雷貝爾 / Kraber", "desc": "Kraber。", "desc_tw": "Kraber。", "desc_hk": "Kraber。", "example": "A: 何入ってた？(里面有什么)\nB: ケアパケにクレーバー。(空投里有克雷贝尔)", "example_tw": "A: 何入ってた？(裡面有什麼)\nB: ケアパケにクレーバー。(空投裡有克雷貝爾)", "example_hk": "A: 何入ってた？(入面有咩)\nB: ケアパケにクレーバー。(空投有克雷貝爾)", "tags": ["LOOT"], "stars": 3 },
  { "id": "a37", "cat": "APEX", "term": "アンチ", "kana": "あんち", "romaji": "Anchi", "level": 1, "meaning": "毒圈", "meaning_tw": "縮圈", "meaning_hk": "圈", "desc": "Zone。", "desc_tw": "Zone。", "desc_hk": "Zone。", "example": "リングが動いてる。\n(圈在动了。)", "example_tw": "リングが動いてる。\n(圈在動了。)", "example_hk": "リングが動いてる。\n(圈郁緊。)", "tags": ["SYSTEM", "CALLOUT"], "stars": 3 },
  { "id": "a38", "cat": "APEX", "term": "安置", "kana": "あんち", "romaji": "Anchi", "level": 1, "meaning": "安全区", "meaning_tw": "安全區", "meaning_hk": "安全區", "desc": "Safe zone。发音同毒圈。", "desc_tw": "Safe zone。發音同毒圈。", "desc_hk": "Safe zone。", "example": "A: どこ守る？(守哪里)\nB: ここ安置だね。(这里是安全区)", "example_tw": "A: どこ守る？(守哪裡)\nB: ここ安置だね。(這裡安全區)", "example_hk": "A: どこ守る？(守邊度)\nB: ここ安置だね。(呢度安全區)", "tags": ["CALLOUT"], "stars": 3 },
  { "id": "a39", "cat": "APEX", "term": "ポータル", "kana": "ぽーたる", "romaji": "Pootaru", "level": 1, "meaning": "传送门", "meaning_tw": "傳送門", "meaning_hk": "門", "desc": "Portal。", "desc_tw": "Portal。", "desc_hk": "Portal。", "example": "ポータルで引こう。\n(用传送门撤退。)", "example_tw": "ポータルで引こう。\n(用傳送門撤退。)", "example_hk": "ポータルで引こう。\n(用門走。)", "tags": ["SKILL"], "stars": 3 },
  { "id": "a40", "cat": "APEX", "term": "ジップ", "kana": "じっぷ", "romaji": "Jippu", "level": 1, "meaning": "滑索", "meaning_tw": "滑索 / 繩索", "meaning_hk": "繩", "desc": "Zipline。", "desc_tw": "Zipline。", "desc_hk": "Zipline。", "example": "A: 上行く？(上去吗)\nB: ジップハウス。(去滑索房)", "example_tw": "A: 上行く？(上去嗎)\nB: ジップハウス。(去繩索房)", "example_hk": "A: 上行く？(上唔上去)\nB: ジップハウス。(去繩索房)", "tags": ["SYSTEM", "CALLOUT"], "stars": 3 },
  { "id": "a41", "cat": "APEX", "term": "ジャンプタワー", "kana": "じゃんぷたわー", "romaji": "Janpu Tawaa", "level": 1, "meaning": "气球塔", "meaning_tw": "跳躍塔 / 氣球", "meaning_hk": "氣球", "desc": "Jump tower。", "desc_tw": "Jump tower。", "desc_hk": "Jump tower。", "example": "A: 移動どうする？(怎么走)\nB: ジャンプタワーで飛ぼう。(坐气球飞吧)", "example_tw": "A: 移動どうする？(怎麼走)\nB: ジャンプタワーで飛ぼう。(坐氣球飛吧)", "example_hk": "A: 移動どうする？(點走)\nB: ジャンプタワーで飛ぼう。(坐氣球飛啦)", "tags": ["SYSTEM"], "stars": 2 },
  { "id": "a42", "cat": "APEX", "term": "蘇生", "kana": "そせい", "romaji": "Sosei", "level": 1, "meaning": "复活/拉人", "meaning_tw": "復活 / 拉人", "meaning_hk": "拉人 / 救人", "desc": "Revive。", "desc_tw": "Revive。", "desc_hk": "Revive。", "example": "A: 敵引いた。(敌人走了)\nB: 蘇生通せる？(能拉我吗？)", "example_tw": "A: 敵引いた。(敵人走了)\nB: 蘇生通せる？(能拉我嗎？)", "example_hk": "A: 敵引いた。(敵人走咗)\nB: 蘇生通せる？(救唔救到我？)", "tags": ["HELP", "COMBAT"], "stars": 3 },
  { "id": "a43", "cat": "APEX", "term": "リスポーン", "kana": "りすぽーん", "romaji": "Risupoon", "level": 1, "meaning": "复活台复活", "meaning_tw": "重生", "meaning_hk": "復活", "desc": "Respawn。", "desc_tw": "Respawn。", "desc_hk": "Respawn。", "example": "A: バナー拾った。(捡到牌子了)\nB: ビーコンでリスポーン。(去复活台复活)", "example_tw": "A: バナー拾った。(撿到牌子了)\nB: ビーコンでリスポーン。(去復活台復活)", "example_hk": "A: バナー拾った。(執到牌了)\nB: ビーコンでリスポーン。(去復活台復活)", "tags": ["HELP"], "stars": 2 },
  { "id": "a44", "cat": "APEX", "term": "フィニッシャー", "kana": "ふぃにっしゃー", "romaji": "Finisshaa", "level": 1, "meaning": "处决", "meaning_tw": "處決", "meaning_hk": "處決", "desc": "Finisher。", "desc_tw": "Finisher。", "desc_hk": "Finisher。", "example": "A: アーマー回復したい。(想回甲)\nB: フィニッシャー入れてる。(正在处决)", "example_tw": "A: アーマー回復したい。(想回甲)\nB: フィニッシャー入れてる。(正在處決)", "example_hk": "A: アーマー回復したい。(想回甲)\nB: フィニッシャー入れてる。(處決緊)", "tags": ["COMBAT"], "stars": 2 },
  { "id": "a45", "cat": "APEX", "term": "屈伸", "kana": "くっしん", "romaji": "Kusshin", "level": 2, "meaning": "蹲起嘲讽", "meaning_tw": "蹲下起立嘲諷", "meaning_hk": "鞭屍 / 蹲起", "desc": "Teabagging。", "desc_tw": "Teabagging。", "desc_hk": "Teabagging。", "example": "A: 煽られた。(被嘲讽了)\nB: 屈伸死体撃ちされた。(被鞭尸还蹲起嘲讽)", "example_tw": "A: 煽られた。(被嘲諷了)\nB: 屈伸死体撃ちされた。(被鞭屍還蹲起嘲諷)", "example_hk": "A: 煽られた。(被嘲諷)\nB: 屈伸死体撃ちされた。(被鞭屍仲要蹲起)", "tags": ["COMBAT", "OUTCOME"], "stars": 2 },
  { "id": "a46", "cat": "APEX", "term": "ハイド", "kana": "はいど", "romaji": "Haido", "level": 2, "meaning": "苟分 / 老六", "meaning_tw": "龜分 / 躲起來", "meaning_hk": "龜 / 鼠分", "desc": "【战术】躲起来争取排名。", "desc_tw": "【戰術】躲起來爭取排名。", "desc_hk": "【戰術】躲起來爭取排名。", "example": "A: 一人になった。(剩我一个了)\nB: 無理せずハイドして。(别打了，苟分吧)", "example_tw": "A: 一人になった。(剩我一個了)\nB: 無理せずハイドして。(別打了，龜分吧)", "example_hk": "A: 一人になった。(剩低我一個)\nB: 無理せずハイドして。(唔好打啦，鼠分算)", "tags": ["COMBAT", "OUTCOME"], "stars": 2 },
  { "id": "a47", "cat": "APEX", "term": "デスボ", "kana": "ですぼ", "romaji": "Desubo", "level": 1, "meaning": "盒子 / 死亡之箱", "meaning_tw": "死亡箱 / 盒子", "meaning_hk": "箱", "desc": "【机制】Death Box。", "desc_tw": "【機制】Death Box。", "desc_hk": "【機制】Death Box。", "example": "A: アーマー割れた。(甲碎了)\nB: デスボから着替えて！(舔包换甲！)", "example_tw": "A: アーマー割れた。(甲碎了)\nB: デスボから着替えて！(舔包換甲！)", "example_hk": "A: アーマー割れた。(甲碎了)\nB: デスボから着替えて！(舔箱換甲！)", "tags": ["SYSTEM", "LOOT"], "stars": 3 },
  { "id": "a48", "cat": "APEX", "term": "ケアパケ", "kana": "けあぱけ", "romaji": "Keapake", "level": 1, "meaning": "空投", "meaning_tw": "空投", "meaning_hk": "空投", "desc": "【机制】Care Package。", "desc_tw": "【機制】Care Package。", "desc_hk": "【機制】Care Package。", "example": "誕生日のプレゼントだ。\n(这是生日礼物。)", "example_tw": "誕生日のプレゼントだ。\n(這是生日禮物。)", "example_hk": "誕生日のプレゼントだ。\n(生日禮物黎架。)", "tags": ["SYSTEM", "LOOT"], "stars": 3 },
  { "id": "a49", "cat": "APEX", "term": "ジャンパ", "kana": "じゃんぱ", "romaji": "Janpa", "level": 1, "meaning": "跳板", "meaning_tw": "跳板", "meaning_hk": "跳板", "desc": "【技能】Octane的跳板。", "desc_tw": "【技能】Octane的跳板。", "desc_hk": "【技能】Octane嘅跳板。", "example": "ジャンパで飛ぼう。\n(坐跳板飞吧。)", "example_tw": "ジャンパで飛ぼう。\n(坐跳板飛吧。)", "example_hk": "ジャンパで飛ぼう。\n(坐跳板飛啦。)", "tags": ["SKILL"], "stars": 3 },
  { "id": "a50", "cat": "APEX", "term": "キルポ", "kana": "きるぽ", "romaji": "Kirupo", "level": 1, "meaning": "击杀分", "meaning_tw": "擊殺分 / 人頭分", "meaning_hk": "人頭分", "desc": "【排位】Kill Point。", "desc_tw": "【排位】Kill Point。", "desc_hk": "【排位】Kill Point。", "example": "A: 戦う？(打吗？)\nB: キルポ欲しい。(想要击杀分)", "example_tw": "A: 戦う？(打嗎？)\nB: キルポ欲しい。(想要人頭分)", "example_hk": "A: 戦う？(打唔打？)\nB: キルポ欲しい。(想要人頭分)", "tags": ["OUTCOME"], "stars": 3 },
  { "id": "a51", "cat": "APEX", "term": "ダブハン", "kana": "だぶはん", "romaji": "Dabuhan", "level": 3, "meaning": "双锤", "meaning_tw": "雙槌", "meaning_hk": "雙槌", "desc": "【徽章】单局4000伤害。", "desc_tw": "【徽章】單局4000傷害。", "desc_hk": "【徽章】單局4000傷害。", "example": "A: あのレイス...(那个恶灵...)\nB: ダブハン持ちだ。(有双锤徽章)", "example_tw": "A: あのレイス...(那個Wraith...)\nB: ダブハン持ちだ。(有雙槌徽章)", "example_hk": "A: あのレイス...(個隻Wraith...)\nB: ダブハン持ちだ。(有雙槌)", "tags": ["OUTCOME", "SYSTEM"], "stars": 2 },
  { "id": "a52", "cat": "APEX", "term": "爪痕", "kana": "つめあと", "romaji": "Tsumeato", "level": 3, "meaning": "骷髅海", "meaning_tw": "骷髏海 / 20殺", "meaning_hk": "骷髏海", "desc": "【徽章】单局20击杀。", "desc_tw": "【徽章】單局20擊殺。", "desc_hk": "【徽章】單局20擊殺。", "example": "A: チャンピオン強そう。(冠军好像很强)\nB: 爪痕ダブハンだ。(是双锤骷髅海)", "example_tw": "A: チャンピオン強そう。(冠軍好像很強)\nB: 爪痕ダブハンだ。(是雙槌骷髏海)", "example_hk": "A: チャンピオン強そう。(冠軍好似好勁)\nB: 爪痕ダブハンだ。(係雙槌骷髏海)", "tags": ["OUTCOME", "SYSTEM"], "stars": 2 },
  { "id": "a53", "cat": "APEX", "term": "カジュアル", "kana": "かじゅある", "romaji": "Kajuaru", "level": 1, "meaning": "匹配 / 休闲模式", "meaning_tw": "一般場 / 休閒", "meaning_hk": "Pub / 休閒", "desc": "【模式】Casual Match。", "desc_tw": "【模式】Casual Match。", "desc_hk": "【模式】Casual Match。", "example": "A: ランク行く？(打排位吗)\nB: 先にカジュアルで。(先打把匹配吧)", "example_tw": "A: ランク行く？(打積分嗎)\nB: 先にカジュアルで。(先打把一般場吧)", "example_hk": "A: ランク行く？(打Rank嗎)\nB: 先にカジュアルで。(打場Pub先)", "tags": ["SYSTEM"], "stars": 3 },
  { "id": "a54", "cat": "APEX", "term": "クラフト", "kana": "くらふと", "romaji": "Kurafuto", "level": 2, "meaning": "制造 / 造东西", "meaning_tw": "製造 / 做東西", "meaning_hk": "造野", "desc": "【动作】Craft。", "desc_tw": "【動作】Craft。", "desc_hk": "【動作】Craft。", "example": "A: バッテリーない。(没大电了)\nB: クラフトしてくる。(我去造一点)", "example_tw": "A: バッテリーない。(沒大電了)\nB: クラフトしてくる。(我去作一點)", "example_hk": "A: バッテリーない。(無大電)\nB: クラフトしてくる。(我去造啲)", "tags": ["LOOT", "SYSTEM"], "stars": 2 },
  { "id": "a55", "cat": "APEX", "term": "ドームファイト", "kana": "どーむふぁいと", "romaji": "Doomu Faito", "level": 3, "meaning": "泡泡战", "meaning_tw": "泡泡戰", "meaning_hk": "罩戰 / 泡泡戰", "desc": "【战术】罩子内近战。", "desc_tw": "【戰術】罩子內近戰。", "desc_hk": "【戰術】罩內近戰。", "example": "A: ジブ出した。(胖子交罩了)\nB: ドームファイトしよう！(打泡泡战！)", "example_tw": "A: ジブ出した。(胖子交罩了)\nB: ドームファイトしよう！(打泡泡戰！)", "example_hk": "A: ジブ出した。(肥仔交罩)\nB: ドームファイトしよう！(打罩戰！)", "tags": ["COMBAT"], "stars": 2 },
  { "id": "a56", "cat": "APEX", "term": "トロール", "kana": "とろーる", "romaji": "Torooru", "level": 2, "meaning": "搞心态 / 演员", "meaning_tw": "戳 / 雷人 / 搞事", "meaning_hk": "搞事 / 戳", "desc": "【行为】Troll。", "desc_tw": "【行為】Troll。", "desc_hk": "【行為】Troll。", "example": "A: 何してんの？(在干嘛啊)\nB: 味方がトロールしてる。(队友在搞心态)", "example_tw": "A: 何してんの？(在幹嘛啊)\nB: 味方がトロールしてる。(隊友在戳)", "example_hk": "A: 何してんの？(做咩啊)\nB: 味方がトロールしてる。(隊友搞事)", "tags": ["OUTCOME"], "stars": 2 },
  { "id": "a57", "cat": "APEX", "term": "チーミング", "kana": "ちーみんぐ", "romaji": "Chiimingu", "level": 2, "meaning": "恶意组队", "meaning_tw": "非法組隊", "meaning_hk": "惡意組隊", "desc": "【违规】Teaming。", "desc_tw": "【違規】Teaming。", "desc_hk": "【違規】Teaming。", "example": "A: 敵6人いる？(对面有6个人？)\nB: チーミングだ、最悪。(非法组队，真恶心)", "example_tw": "A: 敵6人いる？(對面有6個人？)\nB: チーミングだ、最悪。(非法組隊，真噁心)", "example_hk": "A: 敵6人いる？(對面有6個人？)\nB: チーミングだ、最悪。(惡意組隊，真係衰)", "tags": ["OUTCOME"], "stars": 1 },
  { "id": "a58", "cat": "APEX", "term": "チーター", "kana": "ちーたー", "romaji": "Chiitaa", "level": 1, "meaning": "外挂", "meaning_tw": "外掛", "meaning_hk": "外掛 / 神仙", "desc": "【违规】Cheater。", "desc_tw": "【違規】Cheater。", "desc_hk": "【違規】Cheater。", "example": "A: 全部ヘッショ...(全是爆头...)\nB: あれチーターだわ。(那是挂)", "example_tw": "A: 全部ヘッショ...(全是爆頭...)\nB: あれチーターだわ。(那是外掛)", "example_hk": "A: 全部ヘッショ...(全部爆頭...)\nB: あれチーターだわ。(個個外掛黎)", "tags": ["OUTCOME"], "stars": 3 },
  { "id": "a59", "cat": "APEX", "term": "ナイファイ", "kana": "ないふぁい", "romaji": "NaiFai", "level": 1, "meaning": "打得不错", "meaning_tw": "打得不錯 / 惜敗", "meaning_hk": "打得好", "desc": "【鼓励】Nice Fight。", "desc_tw": "【鼓勵】Nice Fight。", "desc_hk": "【鼓勵】Nice Fight。", "example": "A: 負けたごめん。(输了抱歉)\nB: ナイファイ！惜しかった。(打得不错！尽力了)", "example_tw": "A: 負けたごめん。(輸了抱歉)\nB: ナイファイ！惜しかった。(打得不錯！盡力了)", "example_hk": "A: 負けたごめん。(輸咗Sorry)\nB: ナイファイ！惜しかった。(打得好！盡力了)", "tags": ["OUTCOME", "COMBAT"], "stars": 3 },
  { "id": "a60", "cat": "APEX", "term": "ドンマイ", "kana": "どんまい", "romaji": "Donmai", "level": 1, "meaning": "没事 / 别在意", "meaning_tw": "沒事 / 別在意", "meaning_hk": "沒事 / Don't Mind", "desc": "【安慰】Don't mind。", "desc_tw": "【安慰】Don't mind。", "desc_hk": "【安慰】Don't mind。", "example": "A: ミスった。(失误了)\nB: ドンマイ、次いこう。(没事，下一把)", "example_tw": "A: ミスった。(失誤了)\nB: ドンマイ、次いこう。(沒事，下一把)", "example_hk": "A: ミスった。(失誤咗)\nB: ドンマイ、次いこう。(沒事，下一場)", "tags": ["OUTCOME", "HELP"], "stars": 3 },
  { "id": "a61", "cat": "APEX", "term": "レレレ撃ち", "kana": "れれれうち", "romaji": "ReReReUchi", "level": 3, "meaning": "左右横跳射击", "meaning_tw": "左右橫移射擊", "meaning_hk": "左右橫跳", "desc": "【身法】Strafing。", "desc_tw": "【身法】Strafing。", "desc_hk": "【身法】Strafing。", "example": "A: 当たらない...(打不中...)\nB: レレレ撃ちうまいな。(身法好骚啊)", "example_tw": "A: 当たらない...(打不中...)\nB: レレレ撃ちうまいな。(身法好騷啊)", "example_hk": "A: 当たらない...(打唔中...)\nB: レレレ撃ちうまいな。(身法好勁)", "tags": ["COMBAT"], "stars": 2 },

  // ================= OVERWATCH (守望先锋 / 鬥陣特攻) =================
  { "id": "o01", "cat": "OW", "term": "ウルト", "kana": "うると", "romaji": "Uruto", "level": 1, "meaning": "大招", "meaning_tw": "大絕", "meaning_hk": "Ult / 大絕", "desc": "Ult。", "desc_tw": "Ult。", "desc_hk": "Ult。", "example": "A: 状況は？(情况？)\nB: ウルト報告して。(报一下大招)", "example_tw": "A: 状況は？(情況？)\nB: ウルト報告して。(報一下大絕)", "example_hk": "A: 状況は？(情況？)\nB: ウルト報告して。(報一下Ult)", "tags": ["ULT"], "stars": 3 },
  { "id": "o02", "cat": "OW", "term": "ナノ", "kana": "なの", "romaji": "Nano", "level": 1, "meaning": "激素", "meaning_tw": "奈米強化", "meaning_hk": "激素 / Nano", "desc": "Nano Boost (安娜)。", "desc_tw": "Nano Boost (安娜)。", "desc_hk": "Nano Boost (安娜)。", "example": "ナノ溜まった。\n(激素好了。)", "example_tw": "奈米強化好了。\n(奈米強化好了。)", "example_hk": "有激素了。\n(有激素了。)", "tags": ["ULT"], "stars": 3 },
  { "id": "o03", "cat": "OW", "term": "サージ", "kana": "さーじ", "romaji": "Saaji", "level": 2, "meaning": "重力喷涌 (吸)", "meaning_tw": "地心引力", "meaning_hk": "吸 / 重力", "desc": "Grav (查莉娅)。", "desc_tw": "Grav (查莉婭)。", "desc_hk": "Grav (Zarya)。", "example": "A: ウルトある。(有大)\nB: サージに合わせよう。(配合阿贡打)", "example_tw": "A: ウルトある。(有大)\nB: サージに合わせよう。(配合重力打)", "example_hk": "A: ウルトある。(有大)\nB: サージに合わせよう。(配合吸打)", "tags": ["ULT"], "stars": 2 },
  { "id": "o04", "cat": "OW", "term": "龍剣", "kana": "りゅうけん", "romaji": "Ryuuken", "level": 2, "meaning": "拔刀", "meaning_tw": "龍一文字", "meaning_hk": "拔刀", "desc": "Dragonblade (源氏)。", "desc_tw": "Dragonblade (源氏)。", "desc_hk": "Dragonblade (Genji)。", "example": "龍剣警戒して。\n(注意对面拔刀。)", "example_tw": "龍剣警戒して。\n(小心拔刀。)", "example_hk": "龍剣警戒して。\n(小心拔刀。)", "tags": ["ULT"], "stars": 3 },
  { "id": "o05", "cat": "OW", "term": "ハック", "kana": "はっく", "romaji": "Hakku", "level": 1, "meaning": "入侵/黑", "meaning_tw": "駭入", "meaning_hk": "黑 / Hack", "desc": "Hack (黑影)。", "desc_tw": "Hack (駭影)。", "desc_hk": "Hack (Sombra)。", "example": "ソンブラ、ハックお願い。\n(黑影，黑一下。)", "example_tw": "ソンブラ、ハックお願い。\n(駭影，駭一下。)", "example_hk": "ソンブラ、ハックお願い。\n(Sombra，Hack一下。)", "tags": ["COMBAT"], "stars": 3 },
  { "id": "o06", "cat": "OW", "term": "阻害", "kana": "そがい", "romaji": "Sogai", "level": 2, "meaning": "禁疗", "meaning_tw": "禁療", "meaning_hk": "禁療", "desc": "Anti-nade (安娜)。", "desc_tw": "Anti-nade (安娜)。", "desc_hk": "Anti-nade (安娜)。", "example": "A: ビン投げた。(扔瓶子了)\nB: 敵タンク阻害！(对面T禁疗了！)", "example_tw": "A: ビン投げた。(丟瓶子了)\nB: 敵タンク阻害！(對面坦禁療了！)", "example_hk": "A: ビン投げた。(丟瓶了)\nB: 敵タンク阻害！(對面坦禁療！)", "tags": ["COMBAT"], "stars": 2 },
  { "id": "o07", "cat": "OW", "term": "鈴", "kana": "すず", "romaji": "Suzu", "level": 2, "meaning": "铃铛", "meaning_tw": "御狐鈴", "meaning_hk": "鈴", "desc": "Suzu (雾子)。", "desc_tw": "Suzu (霧子)。", "desc_hk": "Suzu (Kiriko)。", "example": "鈴投げて！\n(扔铃铛！)", "example_tw": "鈴投げて！\n(丟御狐鈴！)", "example_hk": "鈴投げて！\n(丟鈴！)", "tags": ["COMBAT"], "stars": 2 },
  { "id": "o08", "cat": "OW", "term": "芋", "kana": "いも", "romaji": "Imo", "level": 2, "meaning": "锁血立场", "meaning_tw": "維生力場", "meaning_hk": "鎖血 / 燈", "desc": "Lamp (巴蒂)。形状像芋头。", "desc_tw": "Lamp (巴蒂)。形狀像芋頭。", "desc_hk": "Lamp (Bap)。形狀像芋頭。", "example": "A: 死なない！(打不死！)\nB: 芋壊して！(把锁血打了！)", "example_tw": "A: 死なない！(打不死！)\nB: 芋壊して！(把立場打了！)", "example_hk": "A: 死なない！(打唔死！)\nB: 芋壊して！(打鎖血！)", "tags": ["COMBAT"], "stars": 2 },
  { "id": "o09", "cat": "OW", "term": "狐", "kana": "きつね", "romaji": "Kitsune", "level": 1, "meaning": "狐狸/快得一批", "meaning_tw": "狐狸/快得一批", "meaning_hk": "狐狸", "desc": "Kitsune Rush (雾子)。", "desc_tw": "Kitsune Rush (霧子)。", "desc_hk": "Kitsune Rush (Kiriko)。", "example": "狐の鍵を導け！\n(让狐狸指引大家！)", "example_tw": "狐の鍵を導け！\n(讓狐狸指引大家！)", "example_hk": "狐の鍵を導け！\n(比狐狸帶路！)", "tags": ["ULT"], "stars": 2 },
  { "id": "o10", "cat": "OW", "term": "デッドアイ", "kana": "でっどあい", "romaji": "Deddoai", "level": 1, "meaning": "午时已到", "meaning_tw": "彈無虛發", "meaning_hk": "午時已到 / High Noon", "desc": "Deadeye (卡西迪)。", "desc_tw": "Deadeye (卡西迪)。", "desc_hk": "Deadeye (Cassidy)。", "example": "デッドアイで牽制。\n(用午时已到压制。)", "example_tw": "デッドアイで牽制。\n(用彈無虛發壓制。)", "example_hk": "デッドアイで牽制。\n(用High Noon壓制。)", "tags": ["ULT"], "stars": 3 },
  { "id": "o11", "cat": "OW", "term": "EMP", "kana": "いーえむぴー", "romaji": "Ii Em Pii", "level": 1, "meaning": "电磁脉冲", "meaning_tw": "電磁脈衝", "meaning_hk": "EMP", "desc": "EMP (黑影)。", "desc_tw": "EMP (駭影)。", "desc_hk": "EMP (Sombra)。", "example": "EMP撃つよ。\n(我要放EMP了。)", "example_tw": "EMP撃つよ。\n(我要放EMP了。)", "example_hk": "EMP撃つよ。\n(我放EMP啦。)", "tags": ["ULT"], "stars": 3 },
  { "id": "o12", "cat": "OW", "term": "シャッター", "kana": "しゃったー", "romaji": "Shattaa", "level": 1, "meaning": "裂地猛击 (拍)", "meaning_tw": "地裂擊", "meaning_hk": "拍 / 裂地", "desc": "Shatter (大锤)。", "desc_tw": "Shatter (萊因)。", "desc_hk": "Shatter (Rein)。", "example": "シャッター入った！\n(拍到了！/ 裂地中了！)", "example_tw": "シャッター入った！\n(地裂擊大到了！)", "example_hk": "シャッター入った！\n(拍中咗！)", "tags": ["ULT"], "stars": 3 },
  { "id": "o13", "cat": "OW", "term": "虹彩", "kana": "こうさい", "romaji": "Kousai", "level": 3, "meaning": "圣", "meaning_tw": "超凡入聖", "meaning_hk": "圣", "desc": "Transcendence (禅雅塔)。", "desc_tw": "Transcendence (禪雅塔)。", "desc_hk": "Transcendence (Zenyatta)。", "example": "虹彩残ってる？\n(还有圣吗？)", "example_tw": "虹彩残ってる？\n(還有聖嗎？)", "example_hk": "虹彩残ってる？\n(仲有冇聖？)", "tags": ["ULT"], "stars": 2 },
  { "id": "o14", "cat": "OW", "term": "ビート", "kana": "びーと", "romaji": "Biito", "level": 2, "meaning": "音障", "meaning_tw": "音浪屏障", "meaning_hk": "音障 / Beat", "desc": "Beat (卢西奥)。", "desc_tw": "Beat (路西歐)。", "desc_hk": "Beat (Lucio)。", "example": "ビート・ドロップ！\n(哦在这停顿！)", "example_tw": "ビート・ドロップ！\n(來點音樂！)", "example_hk": "ビート・ドロップ！\n(Drop Beat！)", "tags": ["ULT"], "stars": 2 },
  { "id": "o15", "cat": "OW", "term": "コピー", "kana": "こぴー", "romaji": "Kopii", "level": 1, "meaning": "人格复制", "meaning_tw": "人格複製", "meaning_hk": "複製", "desc": "Duplicate (回声)。", "desc_tw": "Duplicate (回音)。", "desc_hk": "Duplicate (Echo)。", "example": "タンクをコピーする。\n(复制坦克。)", "example_tw": "タンクをコピーする。\n(複製肉盾。)", "example_hk": "タンクをコピーする。\n(複製Tank。)", "tags": ["ULT"], "stars": 2 },
  { "id": "o16", "cat": "OW", "term": "集合", "kana": "しゅうごう", "romaji": "Shuugou", "level": 1, "meaning": "集合", "meaning_tw": "集合", "meaning_hk": "集合", "desc": "Group up。", "desc_tw": "Group up。", "desc_hk": "Group up。", "example": "A: バラバラだ。(太散了)\nB: リスポーンで集合。(在重生点集合)", "example_tw": "A: バラバラだ。(太散了)\nB: リスポーンで集合。(在重生點集合)", "example_hk": "A: バラバラだ。(太散了)\nB: リスポーンで集合。(係重生點集合)", "tags": ["COMBAT", "SYSTEM"], "stars": 3 },
  { "id": "o17", "cat": "OW", "term": "引く", "kana": "ひく", "romaji": "Hiku", "level": 1, "meaning": "撤退", "meaning_tw": "撤退", "meaning_hk": "撤退", "desc": "Back。", "desc_tw": "Back。", "desc_hk": "Back。", "example": "A: 押されてる。(被压了)\nB: 当たりすぎ、引こう。(别打了，撤)", "example_tw": "A: 押されてる。(被壓了)\nB: 当たりすぎ、引こう。(別打了，撤)", "example_hk": "A: 押されてる。(被壓緊)\nB: 当たりすぎ、引こう。(唔好打，走)", "tags": ["COMBAT"], "stars": 3 },
  { "id": "o18", "cat": "OW", "term": "フォーカス", "kana": "ふぉーかす", "romaji": "Fookasu", "level": 1, "meaning": "集火", "meaning_tw": "集火", "meaning_hk": "集火 / Focus", "desc": "Focus。", "desc_tw": "Focus。", "desc_hk": "Focus。", "example": "A: 誰やる？(打谁)\nB: マーシーフォーカス！(集火天使！)", "example_tw": "A: 誰やる？(打誰)\nB: マーシーフォーカス！(集火慈悲！)", "example_hk": "A: 誰やる？(打邊個)\nB: マーシーフォーカス！(Focus Mercy！)", "tags": ["COMBAT"], "stars": 3 },
  { "id": "o19", "cat": "OW", "term": "ワンパン", "kana": "わんぱん", "romaji": "Wanpan", "level": 1, "meaning": "秒杀", "meaning_tw": "秒殺", "meaning_hk": "秒殺", "desc": "One shot。", "desc_tw": "One shot。", "desc_hk": "One shot。", "example": "A: 死んだ。(死了)\nB: ソジョーンにワンパンされた。(被索杰恩秒了)", "example_tw": "A: 死んだ。(死了)\nB: ソジョーンにワンパンされた。(被索潔恩秒了)", "example_hk": "A: 死んだ。(死咗)\nB: ソジョーンにワンパンされた。(被Sojourn秒咗)", "tags": ["COMBAT"], "stars": 2 },
  { "id": "o20", "cat": "OW", "term": "ヒール", "kana": "ひーる", "romaji": "Hiiru", "level": 1, "meaning": "奶", "meaning_tw": "補血 / 奶", "meaning_hk": "奶 / 補血", "desc": "Heal。", "desc_tw": "Heal。", "desc_hk": "Heal。", "example": "A: 死にそう。(快死了)\nB: ヒールプリーズ！(求奶！)", "example_tw": "A: 死にそう。(快死了)\nB: ヒールプリーズ！(求補！)", "example_hk": "A: 死にそう。(快死)\nB: ヒールプリーズ！(求奶！)", "tags": ["COMBAT"], "stars": 3 },
  { "id": "o21", "cat": "OW", "term": "ペイロード", "kana": "ぺいろーど", "romaji": "Peiroodo", "level": 1, "meaning": "车", "meaning_tw": "車 / 運載目標", "meaning_hk": "車", "desc": "Payload。", "desc_tw": "Payload。", "desc_hk": "Payload。", "example": "A: 敵引いた。(敌人退了)\nB: ペイロード進めて。(推车)", "example_tw": "A: 敵引いた。(敵人退了)\nB: ペイロード進めて。(推車)", "example_hk": "A: 敵引いた。(敵人退了)\nB: ペイロード進めて。(推車)", "tags": ["SYSTEM"], "stars": 3 },
  { "id": "o22", "cat": "OW", "term": "ポイント", "kana": "ぽいんと", "romaji": "Pointo", "level": 1, "meaning": "点", "meaning_tw": "點", "meaning_hk": "點", "desc": "Point。", "desc_tw": "Point。", "desc_hk": "Point。", "example": "A: 時間ない。(没时间了)\nB: ポイント踏んで！(踩点！)", "example_tw": "A: 時間ない。(沒時間了)\nB: ポイント踏んで！(踩點！)", "example_hk": "A: 時間ない。(沒時間了)\nB: ポイント踏んで！(踩點！)", "tags": ["SYSTEM"], "stars": 3 },
  { "id": "o23", "cat": "OW", "term": "高台", "kana": "たかだい", "romaji": "Takadai", "level": 1, "meaning": "高台", "meaning_tw": "高台", "meaning_hk": "高台", "desc": "High ground。", "desc_tw": "High ground。", "desc_hk": "High ground。", "example": "A: ソルジャーどこ？(76在哪)\nB: 高台から撃つ。(在高台输出)", "example_tw": "A: ソルジャーどこ？(76在哪)\nB: 高台から撃つ。(在高台輸出)", "example_hk": "A: ソルジャーどこ？(76係邊)\nB: 高台から撃つ。(係高台射緊)", "tags": ["COMBAT"], "stars": 2 },
  { "id": "o24", "cat": "OW", "term": "裏", "kana": "うら", "romaji": "Ura", "level": 1, "meaning": "绕后", "meaning_tw": "繞後", "meaning_hk": "後面 / 繞後", "desc": "Behind。", "desc_tw": "Behind。", "desc_hk": "Behind。", "example": "A: サポ守って。(保一下辅助)\nB: 裏にトレーサー！(后面有猎空！)", "example_tw": "A: サポ守って。(保一下輔助)\nB: 裏にトレーサー！(後面有閃光！)", "example_hk": "A: サポ守って。(保一下輔助)\nB: 裏にトレーサー！(後面有Tracer！)", "tags": ["COMBAT"], "stars": 2 },
  { "id": "o25", "cat": "OW", "term": "C9", "kana": "しーないん", "romaji": "C Nine", "level": 3, "meaning": "C9", "meaning_tw": "C9", "meaning_hk": "C9", "desc": "赢了团战输了车。", "desc_tw": "贏了團戰輸了車。", "desc_hk": "贏了團戰輸了車。", "example": "A: 離れすぎた。(离太远了)\nB: まじC9じゃんw(真C9了w)", "example_tw": "A: 離れすぎた。(離太遠了)\nB: まじC9じゃんw(真C9了w)", "example_hk": "A: 離れすぎた。(離太遠了)\nB: まじC9じゃんw(真係C9了w)", "tags": ["COMBAT", "SYSTEM"], "stars": 1 },
  { "id": "o26", "cat": "OW", "term": "ピック変更", "kana": "ぴっくへんこう", "romaji": "Pikku Henkou", "level": 2, "meaning": "换英雄", "meaning_tw": "換角", "meaning_hk": "轉陣 / 換英", "desc": "Switch hero。", "desc_tw": "Switch hero。", "desc_hk": "Switch hero。", "example": "A: 進まないな。(推不动啊)\nB: ピック変更頼む。(被针对了，换个英雄吧)", "example_tw": "A: 進まないな。(推不動啊)\nB: ピック変更頼む。(被針對了，換隻吧)", "example_hk": "A: 進まないな。(推唔郁)\nB: ピック変更頼む。(被針對了，換隻啦)", "tags": ["SYSTEM"], "stars": 2 },
  { "id": "o27", "cat": "OW", "term": "フランカー", "kana": "ふらんかー", "romaji": "Furankaa", "level": 2, "meaning": "狗位", "meaning_tw": "側翼 / 狗位", "meaning_hk": "側翼 / 狗", "desc": "Flanker。", "desc_tw": "Flanker。", "desc_hk": "Flanker。", "example": "A: サポきつい。(辅助很难受)\nB: フランカーうざい。(狗位真烦)", "example_tw": "A: サポきつい。(輔助很難受)\nB: フランカーうざい。(側翼真煩)", "example_hk": "A: サポきつい。(輔助好難搞)\nB: フランカーうざい。(隻狗好煩)", "tags": ["ROLE"], "stars": 2 },
  { "id": "o28", "cat": "OW", "term": "盾", "kana": "たて", "romaji": "Tate", "level": 1, "meaning": "盾", "meaning_tw": "盾", "meaning_hk": "盾", "desc": "Shield。", "desc_tw": "Shield。", "desc_hk": "Shield。", "example": "A: 前出れる？(能压吗)\nB: 盾割れそう。(盾要碎了)", "example_tw": "A: 前出れる？(能壓嗎)\nB: 盾割れそう。(盾要碎了)", "example_hk": "A: 前出れる？(出唔出得)\nB: 盾割れそう。(盾要碎了)", "tags": ["COMBAT"], "stars": 3 },
  { "id": "o29", "cat": "OW", "term": "ダイブ", "kana": "だいぶ", "romaji": "Daibu", "level": 2, "meaning": "放狗/跳脸", "meaning_tw": "放狗 / 跳臉", "meaning_hk": "放狗 / Dive", "desc": "Dive。", "desc_tw": "Dive。", "desc_hk": "Dive。", "example": "A: 構成どうする？(阵容咋办)\nB: ダイブ構成でいこう。(打放狗吧)", "example_tw": "A: 構成どうする？(陣容怎辦)\nB: ダイブ構成でいこう。(打放狗吧)", "example_hk": "A: 構成どうする？(陣容點)\nB: ダイブ構成でいこう。(打Dive啦)", "tags": ["ROLE", "COMBAT"], "stars": 2 },
  { "id": "o30", "cat": "OW", "term": "ポーク", "kana": "ぽーく", "romaji": "Pooku", "level": 2, "meaning": "长枪消耗", "meaning_tw": "長槍消耗", "meaning_hk": "Poke / 消耗", "desc": "Poke。", "desc_tw": "Poke。", "desc_hk": "Poke。", "example": "A: 睨み合いだね。(僵持住了)\nB: ポーク合戦。(在那互耗呢)", "example_tw": "A: 睨み合いだね。(僵持住了)\nB: ポーク合戦。(在那互耗呢)", "example_hk": "A: 睨み合いだね。(僵持住咗)\nB: ポーク合戦。(係度Poke緊)", "tags": ["ROLE", "COMBAT"], "stars": 2 }
];
